import { mkdir } from 'node:fs/promises';
import { basename, join, resolve, sep } from 'node:path';
import { toErrorMessage } from '../utils/error.js';
import { NOTHING_TO_COMMIT } from './worktree-conflict-resolution-contracts.js';
import { parseConflictPaths } from './worktree-git.js';
import {
  cleanupAllManaged,
  cleanupStale,
  listManaged,
  removeBranch,
  removeOne,
} from './worktree-managed-ops.js';
import { WorktreeManagerCore } from './worktree-manager-core.js';
import type { AllocateOpts, MergeOpts, MergeResult, WorktreeHandle } from './worktree-types.js';

export { assertSafePath, parseConflictPaths } from './worktree-git.js';
// Re-exported so `worktree-manager.js` stays the import site for consumers.
export type {
  AllocateOpts,
  MergeOpts,
  MergeResult,
  RunResult,
  WorktreeHandle,
  WorktreeManagerOptions,
  WorktreeStatus,
} from './worktree-types.js'; // no-op commit; "added": untracked exist
/**
 * Owns the git-worktree lifecycle for isolated, parallel work units. Shells out
 * to `git` directly (never via the `git` *tool*) so it can target arbitrary
 * worktree directories without the tool's permission gate or `findGitDir`
 * resolution, and so `@wrongstack/core` keeps no dependency on `@wrongstack/tools`.
 */
export class WorktreeManager extends WorktreeManagerCore {
  /** Create a fresh worktree + branch forked from the current base branch. */
  async allocate(ownerId: string, opts: AllocateOpts = {}): Promise<WorktreeHandle> {
    const existing = this.handles.get(ownerId);
    // 'committing' is a live, owned state too: an in-flight or completed-but-
    // unmerged commit means the owner still owns this worktree, and
    // re-allocation must reuse it instead of minting a duplicate checkout and
    // branch that orphan the first one.
    if (
      existing &&
      (existing.status === 'allocating' ||
        existing.status === 'active' ||
        existing.status === 'committing')
    ) {
      return existing;
    }

    const slug = this.makeSlug(opts.slugHint ?? ownerId);
    const branch = `wstack/ap/${slug}`;
    const dir = join(this.worktreesRoot(), slug);
    // Guard: slug is generated by makeSlug() which strips non-alphanumeric
    // chars, but double-check the dir resolves inside projectRoot so a
    // malicious slugHint with path traversal can't escape the worktrees dir.
    const absDir = resolve(dir);
    const absRoot = resolve(this.projectRoot);
    if (!absDir.startsWith(absRoot + sep)) {
      throw new Error(`Worktree dir "${absDir}" resolves outside project root`);
    }

    const baseBranch = opts.baseBranch ?? (await this.detectBaseBranch());

    const handle: WorktreeHandle = {
      id: slug,
      ownerId,
      ownerLabel: opts.ownerLabel ?? opts.slugHint ?? ownerId,
      slug,
      dir,
      branch,
      baseBranch,
      status: 'allocating',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      insertions: 0,
      deletions: 0,
      files: 0,
    };
    this.handles.set(ownerId, handle);

    try {
      await mkdir(this.worktreesRoot(), { recursive: true });
      // git worktree add -b <branch> <path> <base> — path before commit-ish.
      const res = await this.runGit(
        ['worktree', 'add', '-b', branch, dir, baseBranch],
        this.projectRoot,
      );
      if (res.code !== 0) {
        return this.fail(handle, res.stderr || 'git worktree add failed', 'allocate');
      }
    } catch (err) {
      return this.fail(handle, toErrorMessage(err), 'allocate');
    }

    this.setStatus(handle, 'active');
    this.emit('worktree.allocated', {
      handleId: handle.id,
      ownerId: handle.ownerId,
      ownerLabel: handle.ownerLabel,
      slug: handle.slug,
      dir: handle.dir,
      branch: handle.branch,
      baseBranch: handle.baseBranch,
    });
    return handle;
  }

  /** Reattach a persisted phase checkout after the process that created it exits. */
  async adopt(
    ownerId: string,
    saved: { dir: string; branch: string; baseBranch: string; ownerLabel?: string | undefined },
  ): Promise<WorktreeHandle> {
    const existing = this.handles.get(ownerId);
    if (existing) return existing;
    const root = resolve(this.worktreesRoot());
    const dir = resolve(saved.dir);
    const slug = basename(dir);
    if (
      dir === root ||
      !dir.startsWith(root + sep) ||
      dir.slice(root.length + 1).includes(sep) ||
      saved.branch !== `wstack/ap/${slug}` ||
      !saved.baseBranch
    ) {
      throw new Error('Goal phase worktree identity is outside the managed checkout root.');
    }
    const managed = await this.listManaged();
    if (
      !managed.worktrees.some(
        (entry) => resolve(entry.dir) === dir && entry.branch === saved.branch,
      )
    ) {
      throw new Error(`Goal phase worktree is no longer available: ${dir}`);
    }
    const now = Date.now();
    const handle: WorktreeHandle = {
      id: slug,
      ownerId,
      ownerLabel: saved.ownerLabel ?? ownerId,
      slug,
      dir,
      branch: saved.branch,
      baseBranch: saved.baseBranch,
      status: 'active',
      createdAt: now,
      updatedAt: now,
      insertions: 0,
      deletions: 0,
      files: 0,
    };
    this.handles.set(ownerId, handle);
    this.usedSlugs.add(slug);
    return handle;
  }

  /**
   * Stage everything and commit inside the worktree. `error` is set when the
   * commit was attempted and refused (a pre-commit hook — hooks live in the
   * common git dir, so a repo's husky/lint-staged runs here too — or a locked
   * index): the work is still uncommitted in `handle.dir`, which is NOT the
   * same as "nothing to commit" and must never be treated as a no-op.
   */
  async commitAll(
    handle: WorktreeHandle,
    message: string,
  ): Promise<{ committed: boolean; error?: string | undefined }> {
    this.setStatus(handle, 'committing');
    const added = await this.runGit(['add', '-A'], handle.dir);
    if (added.code !== 0) {
      const error = added.stderr || added.stdout || 'git add failed';
      this.fail(handle, error, 'commit');
      return { committed: false, error };
    }

    // `diff --cached --quiet` exits 1 when there are staged changes, 0 when none.
    const staged = await this.runGit(['diff', '--cached', '--quiet'], handle.dir);
    if (staged.code === 0) {
      this.emitCommitted(handle, false);
      return { committed: false };
    }

    const idArgs = await this.identityArgs(handle.dir);
    const committed = await this.runGit([...idArgs, 'commit', '-m', message], handle.dir);
    if (committed.code !== 0) {
      const error = committed.stderr || committed.stdout || 'git commit failed';
      this.fail(handle, error, 'commit');
      return { committed: false, error };
    }

    const stats = await this.collectStats(handle.dir);
    handle.insertions = stats.insertions;
    handle.deletions = stats.deletions;
    handle.files = stats.files;
    handle.sha = stats.sha;
    handle.updatedAt = Date.now();
    this.emitCommitted(handle, true);
    return { committed: true };
  }

  /** Merge the worktree branch back into the base branch (squash by default). */
  async merge(handle: WorktreeHandle, opts: MergeOpts = {}): Promise<MergeResult> {
    const squash = opts.squash ?? true;
    this.setStatus(handle, 'merging');
    this.emit('worktree.merging', {
      handleId: handle.id,
      ownerId: handle.ownerId,
      branch: handle.branch,
      baseBranch: handle.baseBranch,
    });

    // Only committed work travels with the branch. Uncommitted edits left in
    // the checkout (a refused commitAll) would make this merge a "successful"
    // no-op and the caller's release() would then force-remove the only copy.
    // Fail instead: a failed handle is kept on disk by release().
    const pending = await this.runGit(['status', '--porcelain'], handle.dir);
    if (pending.code === 0 && pending.stdout.trim().length > 0) {
      const reason = `worktree ${handle.branch} has uncommitted changes — kept for review`;
      this.fail(handle, reason, 'merge');
      return { ok: false, stderr: reason };
    }

    const status = await this.runGit(
      ['status', '--porcelain', '--untracked-files=no'],
      this.projectRoot,
    );
    if (status.stdout.trim().length > 0) {
      const reason = 'working tree has uncommitted changes — commit or stash first';
      this.fail(handle, reason, 'merge');
      return { ok: false, stderr: reason };
    }

    const checkout = await this.runGit(['checkout', handle.baseBranch], this.projectRoot);
    if (checkout.code !== 0) {
      this.fail(handle, checkout.stderr || `checkout ${handle.baseBranch} failed`, 'merge');
      return { ok: false, stderr: checkout.stderr };
    }

    // Thread the identity fallback into BOTH merge forms. --no-ff creates its
    // merge commit directly; --squash commits nothing, yet a real three-way
    // merge still refuses to start on an identity-less machine ("Committer
    // identity unknown", exit 128, tree untouched) — which is exactly the
    // "conflict with empty probes" shape Linux CI kept producing.
    const idArgs = await this.identityArgs(this.projectRoot);
    const mergeArgs = squash
      ? [...idArgs, 'merge', '--squash', handle.branch]
      : [...idArgs, 'merge', '--no-ff', handle.branch];
    const merged = await this.runGit(mergeArgs, this.projectRoot);

    // Detect conflicts from BOTH the exit code AND the index/output probes.
    // Some git versions exit 0 on a --squash conflict (when core.whitespace
    // or merge.conflictStyle differ from defaults), leaving markers in the
    // working tree without a non-zero exit signal. Never commit a tree that
    // carries conflict markers — always check the index and parse the output.
    const fromOutput = parseConflictPaths(`${merged.stdout}\n${merged.stderr}`);
    const fromIndex = await this.unmergedFiles();
    let conflictFiles = [...new Set([...fromOutput, ...fromIndex])];
    if (merged.code !== 0 && conflictFiles.length === 0) {
      // Last resort for a git that reports neither: name the files that carry
      // markers, so a resolver is told WHICH files to fix.
      const changed = await this.runGit(['diff', '--name-only', '-z', 'HEAD'], this.projectRoot);
      conflictFiles = await this.conflictMarkedFiles(changed.stdout.split('\0').filter(Boolean));
    }

    if (merged.code !== 0 && conflictFiles.length === 0) {
      // Failed without conflicting (identity, refs, a locked index…). There is
      // nothing for a resolver to resolve: handing it an empty list let it
      // "resolve" an untouched tree, and the stage-everything that followed
      // committed unrelated files. Undo any partial state and report failure.
      await this.runGit(['reset', '--hard', 'HEAD'], this.projectRoot);
      this.fail(handle, merged.stderr || merged.stdout || 'merge failed', 'merge');
      return { ok: false, stderr: merged.stderr };
    }

    if (conflictFiles.length > 0) {
      // Caller-driven resolution: leave the conflicted tree in place, hand the
      // marked files to the resolver, and finalize the merge commit only if it
      // cleared every marker. Any failure falls through to the safe reset below,
      // so the base tree is never left dirty.
      if (opts.resolve) {
        const finalized = await this.tryResolveConflict(handle, conflictFiles, opts);
        if (finalized) return finalized;
      }

      // `merge --squash` leaves no MERGE_HEAD, so `merge --abort` won't work;
      // hard-reset the base tree — the work is safe on the branch.
      await this.runGit(['reset', '--hard', 'HEAD'], this.projectRoot);
      handle.conflictFiles = conflictFiles;
      this.setStatus(handle, 'needs-review', { lastError: merged.stderr });
      this.emit('worktree.conflict', {
        handleId: handle.id,
        ownerId: handle.ownerId,
        branch: handle.branch,
        conflictFiles,
      });
      return { ok: false, conflict: true, conflictFiles, stderr: merged.stderr };
    }

    if (squash) {
      // --squash stages the changes but does not commit; finish the commit.
      const msg = opts.message ?? `merge ${handle.branch} (squash)`;
      const idArgs = await this.identityArgs(this.projectRoot);
      const commit = await this.runGit([...idArgs, 'commit', '-m', msg], this.projectRoot);
      if (commit.code !== 0 && !NOTHING_TO_COMMIT.test(commit.stdout + commit.stderr)) {
        // A refused squash commit (pre-commit hook) leaves the squash staged on
        // base, which then blocks every later merge as "uncommitted changes".
        // Base was clean before the merge and the work is on the branch.
        await this.runGit(['reset', '--hard', 'HEAD'], this.projectRoot);
        this.fail(handle, commit.stderr || commit.stdout || 'squash commit failed', 'merge');
        return { ok: false, stderr: commit.stderr || commit.stdout };
      }
    }

    this.setStatus(handle, 'merged');
    this.emit('worktree.merged', {
      handleId: handle.id,
      ownerId: handle.ownerId,
      branch: handle.branch,
      baseBranch: handle.baseBranch,
      squash,
    });
    return { ok: true };
  }
  /**
   * Force-remove EVERY managed worktree + branch this project owns, without
   * relying on the in-memory `handles` map — so it works post-run (a fresh
   * manager can clean up a previous run's leftovers). Enumerates
   * `git worktree list --porcelain`, removes every checkout living under the
   * `.wrongstack/worktrees` root, deletes every `wstack/ap/*` branch, then prunes.
   * Returns the number of worktrees removed. Never throws — best-effort cleanup.
   */
  async cleanupAllManaged(): Promise<{ removed: number }> {
    return cleanupAllManaged(this.managedOpsContext());
  }

  /**
   * Read-only inventory of this project's managed git artifacts: every worktree
   * checkout under the `.wrongstack/worktrees` root (with its branch, when the
   * checkout has one) plus every `wstack/ap/*` branch. Unlike `cleanupStale` /
   * `cleanupAllManaged` this removes nothing — it powers the WebUI worktree panel
   * so the user can SEE orphans before deciding to clean them. Never throws.
   */
  async listManaged(): Promise<{
    worktrees: Array<{ dir: string; branch?: string | undefined }>;
    branches: string[];
  }> {
    return listManaged(this.managedOpsContext());
  }

  /**
   * Force-remove ONE managed worktree + (optionally) its branch — the targeted
   * counterpart to `cleanupAllManaged`. Used by the WebUI worktree panel's
   * per-row Remove/Discard. Path-guarded so only checkouts under the project's
   * worktrees root can be removed. Best-effort; never throws.
   */
  async removeOne(dir: string, branch?: string | undefined): Promise<{ removed: boolean }> {
    return removeOne(this.managedOpsContext(), dir, branch);
  }

  /** Delete ONE managed branch with no checkout (a branch-only orphan). Never throws. */
  async removeBranch(branch: string): Promise<{ removed: boolean }> {
    return removeBranch(this.managedOpsContext(), branch);
  }
  /**
   * Detect and clean up stale worktrees left behind by crashed subagents.
   *
   * P2 #B6 (sprint2 audit): when a subagent crashes (OOM, SIGKILL), its
   * worktree checkout and branch remain on disk. `cleanupAllManaged()`
   * sweeps everything, but is never called automatically — only via
   * `/worktree clean`. This method runs on Director boot (or any other
   * entry point) to clean up leftovers from a previous crashed run.
   *
   * Unlike `cleanupAllManaged()`, this method is a no-op when no stale
   * worktrees are detected — it doesn't clear in-memory handles or emit
   * events unnecessarily. When stale worktrees ARE found, it delegates
   * to `cleanupAllManaged()` for the actual removal.
   *
   * Returns the number of stale worktrees removed (0 = clean).
   */
  async cleanupStale(): Promise<{ removed: number; detected: number }> {
    return cleanupStale(this.managedOpsContext());
  }
  /**
   * Remove the worktree + branch. Conflicted/failed handles (or `keep:true`)
   * are left on disk for inspection.
   */
  async release(handle: WorktreeHandle, opts: { keep?: boolean | undefined } = {}): Promise<void> {
    const keep = opts.keep || handle.status === 'needs-review' || handle.status === 'failed';
    // `removed` = the checkout actually came off disk. A failed removal
    // (locked dir, OS file handles) leaves the worktree, branch, and commits
    // on disk — keep the handle registered and report kept:true so manager
    // state stays in sync and a later release can retry.
    let removed = false;
    if (!keep) {
      const rm = await this.runGit(['worktree', 'remove', '--force', handle.dir], this.projectRoot);
      removed = rm.code === 0;
      if (removed) {
        await this.runGit(['branch', '-D', handle.branch], this.projectRoot);
        await this.runGit(['worktree', 'prune'], this.projectRoot);
        this.handles.delete(handle.ownerId);
      }
    }
    this.emit('worktree.released', {
      handleId: handle.id,
      ownerId: handle.ownerId,
      branch: handle.branch,
      kept: !removed,
    });
  }

  get(ownerId: string): WorktreeHandle | undefined {
    return this.handles.get(ownerId);
  }

  list(): WorktreeHandle[] {
    return [...this.handles.values()];
  }
}
