// Per-tool detail data for the built-in tool detail pages.
// Generated by scripts/generate-website-tool-catalog.ts from @wrongstack/tools.
// Run `pnpm website:tools:write` after changing a built-in tool contract.

import type { ToolDetail } from './tool-detail-types';

export const toolDetailsPart4: Record<string, ToolDetail> = {
  clarify: {
    longDescription:
      'Record or ask a focused clarification when a missing decision would materially change the implementation. Do not use it for questions that can be answered from the repository.',
    params: [
      {
        name: 'title',
        type: 'string',
        description: 'Short form title.',
      },
      {
        name: 'description',
        type: 'string',
        description: 'Why these answers are needed.',
      },
      {
        name: 'submitLabel',
        type: 'string',
        description: 'Submit button label.',
      },
      {
        name: 'question',
        type: 'string',
      },
      {
        name: 'context',
        type: 'string',
      },
      {
        name: 'type',
        type: "'single_select' | 'multi_select' | 'text'",
      },
      {
        name: 'options',
        type: 'Array<string | object>',
      },
      {
        name: 'recommendedOption',
        type: 'string',
      },
      {
        name: 'recommendedOptions',
        type: 'string[]',
      },
      {
        name: 'recommendedText',
        type: 'string',
      },
      {
        name: 'recommendationReason',
        type: 'string',
      },
      {
        name: 'isMultiSelect',
        type: 'boolean',
      },
      {
        name: 'is_multi_select',
        type: 'boolean',
      },
      {
        name: 'allowCustomResponse',
        type: 'boolean',
      },
      {
        name: 'required',
        type: 'boolean',
      },
      {
        name: 'placeholder',
        type: 'string',
      },
      {
        name: 'questions',
        type: 'object[]',
      },
      {
        name: 'tabs',
        type: 'object[]',
      },
    ],
    notes: ['Use only for high-cost irreversible forks; adopt established defaults autonomously.'],
  },
  tool_use: {
    longDescription:
      'Invoke a registered tool by its exact name, including one not listed in this request. Use it for a tool found through tool_search; the call still goes through the same permission and capability checks as a direct call.',
    params: [
      {
        name: 'tool',
        type: 'string',
        required: true,
        description:
          'The exact registered name of the tool to invoke (e.g. "bash", "read", "codebase-search").',
      },
      {
        name: 'input',
        type: 'object',
        description: "The input object matching the target tool's inputSchema.",
      },
    ],
    notes: [
      'Only use when you are certain of the exact tool name and its expected input shape.',
      'Prefer using the normal tool calling mechanism when possible.',
      'Very useful in batch-tool-use or when orchestrating complex workflows programmatically.',
    ],
  },
  'codebase-index': {
    longDescription:
      'Build or refresh the local semantic codebase index, optionally for selected languages. Use it when index results are absent or stale; force performs a full reindex.',
    params: [
      {
        name: 'force',
        type: 'boolean',
        description:
          'Force a reindex that ignores mtime/content-hash caches. Without `langs` it clears the index and rebuilds every file; with `langs` it re-parses only those languages and keeps the rest.',
      },
      {
        name: 'langs',
        type: "Array<'c' | 'cpp' | 'csharp' | 'css' | 'dart' | 'elixir' | 'go' | 'graphql' | 'haskell' | 'html' | 'java' | 'js' | 'json' | 'jsx' | 'kotlin' | 'lua' | 'md' | 'other' | 'php' | 'proto' | 'py' | 'r' | 'rs' | 'ruby' | 'scala' | 'shell' | 'sql' | 'svelte' | 'swift' | 'toml' | 'ts' | 'tsx' | 'vue' | 'yaml' | 'zig'>",
        description:
          'Limit reindex to specific languages: c, cpp, csharp, css, dart, elixir, go, graphql, haskell, html, java, js, json, jsx, kotlin, lua, md, other, php, proto, py, r, rs, ruby, scala, shell, sql, svelte, swift, toml, ts, tsx, vue, yaml, zig',
      },
    ],
    notes: [
      'First run (or after major changes): consider `force: true` for a clean rebuild.',
      'Normal usage: call without arguments for fast incremental updates.',
      'Use `langs` to restrict to specific languages if you only care about certain parts of the project.',
    ],
  },
  'codebase-search': {
    longDescription:
      'Search indexed symbols, signatures, and documentation with optional language, kind, path, or LSP-kind filters. Use it for semantic discovery before broad text search.',
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: 'Search query — searches symbol names, signatures, and doc comments',
      },
      {
        name: 'kind',
        type: "'class' | 'interface' | 'enum' | 'type' | 'function' | 'method' | 'var' | 'const' | 'let' | 'property' | 'parameter' | 'namespace' | 'object' | 'literal' | 'schema' | 'struct' | 'trait' | 'impl' | 'static' | 'mod'",
        description: 'Filter by indexed symbol kind',
      },
      {
        name: 'lang',
        type: "'c' | 'cpp' | 'csharp' | 'css' | 'dart' | 'elixir' | 'go' | 'graphql' | 'haskell' | 'html' | 'java' | 'js' | 'json' | 'jsx' | 'kotlin' | 'lua' | 'md' | 'other' | 'php' | 'proto' | 'py' | 'r' | 'rs' | 'ruby' | 'scala' | 'shell' | 'sql' | 'svelte' | 'swift' | 'toml' | 'ts' | 'tsx' | 'vue' | 'yaml' | 'zig'",
        description: 'Filter by indexed language',
      },
      {
        name: 'lspKind',
        type: 'integer',
        description:
          'Filter by LSP SymbolKind number (e.g. 5=Class, 12=Function, 11=Interface, 10=Enum)',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Filter to files matching this path substring',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum results to return (default 20, max 100)',
      },
      {
        name: 'preferLsp',
        type: 'boolean',
        description:
          'Deprecated compatibility hint. This built-in remains index-only; use codebase-lsp-search for live LSP results.',
      },
    ],
    notes: [
      'Use when you need to find where something is defined or used by name.',
      '`kind` filter is very useful (e.g. only functions or only interfaces).',
      'Combine with `file` filter to scope to a specific directory or module.',
    ],
  },
  'codebase-skeleton': {
    longDescription:
      'Extract a compact structural skeleton from a source file or directory, preserving declarations while omitting implementation detail. Use it to understand unfamiliar code quickly.',
    params: [
      {
        name: 'path',
        type: 'string',
        required: true,
        description: 'Relative or absolute file or directory path to extract skeleton for.',
      },
      {
        name: 'includeDocs',
        type: 'boolean',
        description: 'Keep JSDoc / docstrings in the output skeleton (defaults to true).',
      },
      {
        name: 'collapseImports',
        type: 'boolean',
        description: 'Collapse import blocks into a single summary comment (defaults to false).',
      },
      {
        name: 'exportsOnly',
        type: 'boolean',
        description: 'Only include exported/public declarations (defaults to false).',
      },
      {
        name: 'maxFiles',
        type: 'integer',
        description: 'Max files to include if path is a directory (defaults to 20, max 50).',
      },
    ],
    notes: [
      'Prefer before reading large files in full when only contracts and structure are needed.',
    ],
  },
  'codebase-repo-map': {
    longDescription:
      'Generate a centrality-ranked, token-budgeted Repository Map within ~1200 tokens by default: package clusters with their hub file, the repo-wide hotspots, then the signatures of the most central files. Use at the beginning of complex tasks or when navigating unfamiliar repositories to get a bird-eye view of the architecture.',
    params: [
      {
        name: 'maxTokens',
        type: 'integer',
        description:
          'Maximum token budget (approximate) for the map. Defaults to 1200, range 100-20000.',
      },
      {
        name: 'focusFiles',
        type: 'string[]',
        description: 'File paths to prioritize and ensure inclusion in the map.',
      },
    ],
    notes: ['Useful at the start of unfamiliar or repository-wide work.'],
  },
  'codebase-context': {
    longDescription:
      'Find the files and declarations a task touches from a plain-language description. Ranked symbol search seeds a personalised walk over the reference graph, so results include what the matches are structurally attached to, not just what matched by name. Start here for any task spanning more than one file.',
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: 'What you are trying to do or understand, in plain words.',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Number of files to return (default 12, max 50).',
      },
      {
        name: 'symbolsPerFile',
        type: 'integer',
        description: 'Declarations shown per file (default 4, max 20).',
      },
      {
        name: 'pathPrefix',
        type: 'string',
        description: 'Restrict results to this project-relative path prefix.',
      },
    ],
  },
  'codebase-ast-replace': {
    longDescription:
      'Replace a named declaration using source-aware structure instead of fragile text matching. Use it for a function, method, class, interface, or variable when the target is unambiguous.',
    params: [
      {
        name: 'file',
        type: 'string',
        required: true,
        description: 'Target file path (relative to project root or absolute).',
      },
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description:
          'Declaration name (function, method, class, interface, type, enum, variable). Qualify nested members as "ClassName.method" when the bare name is ambiguous. Not a test-case title.',
      },
      {
        name: 'newBody',
        type: 'string',
        required: true,
        description: 'The new body implementation (or complete declaration if target="full").',
      },
      {
        name: 'target',
        type: "'body' | 'full'",
        description:
          "Whether to replace only the inner body ('body', default) or the entire symbol declaration ('full').",
      },
      {
        name: 'checkInvariants',
        type: 'boolean',
        description:
          'Whether to check AST backward-compatibility invariants before write. Defaults to true.',
      },
      {
        name: 'allowBreakingChanges',
        type: 'boolean',
        description:
          'Explicitly allow breaking changes (e.g. adding mandatory parameter, removing export) if intentional.',
      },
    ],
    notes: ['Mutating and confirmation-gated.'],
  },
  'codebase-invariant-check': {
    longDescription:
      'Compare candidate code with its original source and report structural invariants that may have changed. Use before writing a risky refactor; it validates but does not modify files.',
    params: [
      {
        name: 'file',
        type: 'string',
        description: 'Path to existing source file to compare against candidate modifications.',
      },
      {
        name: 'originalCode',
        type: 'string',
        description: 'Original source code string (if not reading from an existing file).',
      },
      {
        name: 'modifiedCode',
        type: 'string',
        required: true,
        description: 'The candidate modified code string to validate.',
      },
      {
        name: 'lang',
        type: 'string',
        description: 'Language hint (ts, py, go, rs, etc.). Inferred from file path if omitted.',
      },
    ],
    notes: ['Read-only. Use before applying a breaking signature change.'],
  },
  'codebase-impact-analysis': {
    longDescription:
      'Find likely callers, dependents, related tests, and change risk for a named symbol. Use it before changing a public or widely used declaration.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/class/type name to analyze.',
      },
      {
        name: 'file',
        type: 'string',
        description:
          'Optional file path to disambiguate when multiple symbols share the same name.',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'Whether to traverse transitive callers (callers of callers). Defaults to true.',
      },
    ],
    notes: ['Run before changing public signatures, then pair with codebase-targeted-test.'],
  },
  'codebase-targeted-test': {
    longDescription:
      'Discover and run tests that cover a specified symbol, source file, or explicit test files. Use it for focused regression validation after a change.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        description: 'Symbol name whose covering tests should be discovered and run.',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Source file path whose covering tests should be run.',
      },
      {
        name: 'testFiles',
        type: 'string[]',
        description: 'Explicit list of test files to execute.',
      },
    ],
    notes: ['Execution is confirmation-gated even though it does not edit files.'],
  },
  'security-ast-scan': {
    longDescription:
      'Statically scan source code for supported security patterns and return findings with locations. Use it as a focused code check, not as a substitute for a full security assessment.',
    params: [
      {
        name: 'file',
        type: 'string',
        description: 'File path to scan (relative to project root).',
      },
      {
        name: 'content',
        type: 'string',
        description: 'Direct code string to scan without writing to disk.',
      },
      {
        name: 'rules',
        type: 'string[]',
        description: 'Optional list of rule IDs to filter by.',
      },
    ],
    notes: ['Returns severity-ranked findings with line numbers and remediation guidance.'],
  },
  'codebase-incoming-calls': {
    longDescription:
      'Find indexed call sites that invoke a named function, method, or type, optionally scoped to a file. Use it to estimate breakage before changing an API.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/type name to find callers for',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Scope to a specific file when multiple symbols share the same name',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum call sites to return (default 50, max 200)',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'When true, traverse the full transitive call chain (callers of callers, to unlimited depth). Default false: return only direct callers. Cycle-safe via SQL recursive CTE.',
      },
    ],
  },
  'codebase-outgoing-calls': {
    longDescription:
      'Find indexed symbols called by a named function, method, or type, optionally scoped to a file. Use it to understand dependencies before refactoring behavior.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/type name to find callees for',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Scope to a specific file when multiple symbols share the same name',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum call sites to return (default 50, max 200)',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'When true, traverse the full transitive dependency chain (callees of callees, to unlimited depth). Default false: return only direct callees. Cycle-safe via SQL recursive CTE.',
      },
    ],
  },
  'codebase-stats': {
    longDescription:
      'Report codebase-index health, indexed file and symbol counts, languages, and freshness. Use it before relying on indexed discovery results.',
    params: [],
    notes: [
      'Use to see if the index is up-to-date or needs a refresh.',
      'No arguments required.',
      'Helps avoid wasting tokens on searches against a stale index.',
    ],
  },
  'dead-code-scan': {
    longDescription:
      'Analyze the indexed project for declarations that appear unreachable from configured entry points. Treat results as candidates for review, not automatic deletion instructions.',
    params: [
      {
        name: 'projectRoot',
        type: 'string',
        description: 'Project root (defaults to ctx.projectRoot).',
      },
      {
        name: 'indexDir',
        type: 'string',
        description: 'Override index directory.',
      },
      {
        name: 'entryPoints',
        type: 'string[]',
        description: 'Additional entry-point file paths to seed the scan.',
      },
    ],
    notes: [
      'Read-only (permission: auto, mutating: false). Results are best-effort — dynamic imports, string-based require, and bare `export { X }` re-exports without a local function wrapper create no reference edge and may appear as false dead-code positives.',
      'Entry-point discovery handles root + workspace packages, including pnpm-workspace.yaml packages block and build-output/bin entries mapped back to source.',
    ],
  },
};
