// Per-tool detail data for the built-in tool detail pages.
// Generated by scripts/generate-website-tool-catalog.ts from @wrongstack/tools.
// Run `pnpm website:tools:write` after changing a built-in tool contract.

import type { ToolDetail } from './tool-detail-types';

export const toolDetailsPart4: Record<string, ToolDetail> = {
  'codebase-search': {
    longDescription:
      'Search indexed symbols, signatures, and documentation with optional language, kind, path, or LSP-kind filters. Use it for semantic discovery before broad text search.',
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: 'Search query — searches symbol names, signatures, and doc comments',
      },
      {
        name: 'kind',
        type: "'class' | 'interface' | 'enum' | 'type' | 'function' | 'method' | 'var' | 'const' | 'let' | 'property' | 'parameter' | 'namespace' | 'object' | 'literal' | 'schema' | 'struct' | 'trait' | 'impl' | 'static' | 'mod'",
        description: 'Filter by indexed symbol kind',
      },
      {
        name: 'lang',
        type: "'c' | 'cpp' | 'csharp' | 'css' | 'dart' | 'elixir' | 'go' | 'graphql' | 'haskell' | 'html' | 'java' | 'js' | 'json' | 'jsx' | 'kotlin' | 'lua' | 'md' | 'other' | 'php' | 'proto' | 'py' | 'r' | 'rs' | 'ruby' | 'scala' | 'shell' | 'sql' | 'svelte' | 'swift' | 'toml' | 'ts' | 'tsx' | 'vue' | 'yaml' | 'zig'",
        description: 'Filter by indexed language',
      },
      {
        name: 'lspKind',
        type: 'integer',
        description:
          'Filter by LSP SymbolKind number (e.g. 5=Class, 12=Function, 11=Interface, 10=Enum)',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Filter to files matching this path substring',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum results to return (default 20, max 100)',
      },
      {
        name: 'preferLsp',
        type: 'boolean',
        description:
          'Deprecated compatibility hint. This built-in remains index-only; use codebase-lsp-search for live LSP results.',
      },
    ],
    notes: [
      'Use when you need to find where something is defined or used by name.',
      '`kind` filter is very useful (e.g. only functions or only interfaces).',
      'Combine with `file` filter to scope to a specific directory or module.',
    ],
  },
  'codebase-skeleton': {
    longDescription:
      'Extract a compact structural skeleton from a source file or directory, preserving declarations while omitting implementation detail. Use it to understand unfamiliar code quickly.',
    params: [
      {
        name: 'path',
        type: 'string',
        required: true,
        description: 'Relative or absolute file or directory path to extract skeleton for.',
      },
      {
        name: 'includeDocs',
        type: 'boolean',
        description: 'Keep JSDoc / docstrings in the output skeleton (defaults to true).',
      },
      {
        name: 'collapseImports',
        type: 'boolean',
        description: 'Collapse import blocks into a single summary comment (defaults to false).',
      },
      {
        name: 'exportsOnly',
        type: 'boolean',
        description: 'Only include exported/public declarations (defaults to false).',
      },
      {
        name: 'maxFiles',
        type: 'integer',
        description: 'Max files to include if path is a directory (defaults to 20, max 50).',
      },
    ],
    notes: [
      'Prefer before reading large files in full when only contracts and structure are needed.',
    ],
  },
  'codebase-repo-map': {
    longDescription:
      'Generate a centrality-ranked, token-budgeted Repository Map within ~1200 tokens by default: package clusters with their hub file, the repo-wide hotspots, then the signatures of the most central files. Use at the beginning of complex tasks or when navigating unfamiliar repositories to get a bird-eye view of the architecture.',
    params: [
      {
        name: 'maxTokens',
        type: 'integer',
        description:
          'Maximum token budget (approximate) for the map. Defaults to 1200, range 100-20000.',
      },
      {
        name: 'focusFiles',
        type: 'string[]',
        description: 'File paths to prioritize and ensure inclusion in the map.',
      },
    ],
    notes: ['Useful at the start of unfamiliar or repository-wide work.'],
  },
  'codebase-context': {
    longDescription:
      'Find the files and declarations a task touches from a plain-language description. Ranked symbol search seeds a personalised walk over the reference graph, so results include what the matches are structurally attached to, not just what matched by name. Start here for any task spanning more than one file.',
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: 'What you are trying to do or understand, in plain words.',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Number of files to return (default 12, max 50).',
      },
      {
        name: 'symbolsPerFile',
        type: 'integer',
        description: 'Declarations shown per file (default 4, max 20).',
      },
      {
        name: 'pathPrefix',
        type: 'string',
        description: 'Restrict results to this project-relative path prefix.',
      },
    ],
  },
  'codebase-read-symbol': {
    longDescription:
      'Read the exact implementation of a named declaration (function, method, class, interface, type, enum, variable) from a file using AST parsing. Returns line-numbered code in standard N→content format, eliminating offset guessing and saving context tokens.',
    params: [
      {
        name: 'file',
        type: 'string',
        required: true,
        description: 'Target file path (relative to project root or absolute within project).',
      },
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description:
          'Declaration name (function, method, class, interface, type, enum, variable). Qualify nested members as "ClassName.method" when the bare name is ambiguous. Not a test-case title.',
      },
      {
        name: 'includeDocs',
        type: 'boolean',
        description: 'Keep leading JSDoc / docstrings in the output (defaults to true).',
      },
      {
        name: 'target',
        type: "'full' | 'body'",
        description:
          "Whether to read the full declaration ('full', default) or only the inner block ('body').",
      },
    ],
  },
  'codebase-ast-replace': {
    longDescription:
      'Replace a named declaration using source-aware structure instead of fragile text matching. Use it for a function, method, class, interface, or variable when the target is unambiguous.',
    params: [
      {
        name: 'file',
        type: 'string',
        required: true,
        description: 'Target file path (relative to project root or absolute).',
      },
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description:
          'Declaration name (function, method, class, interface, type, enum, variable). Qualify nested members as "ClassName.method" when the bare name is ambiguous. Not a test-case title.',
      },
      {
        name: 'newBody',
        type: 'string',
        required: true,
        description: 'The new body implementation (or complete declaration if target="full").',
      },
      {
        name: 'target',
        type: "'body' | 'full'",
        description:
          "Whether to replace only the inner body ('body', default) or the entire symbol declaration ('full').",
      },
      {
        name: 'checkInvariants',
        type: 'boolean',
        description:
          'Whether to check AST backward-compatibility invariants before write. Defaults to true.',
      },
      {
        name: 'allowBreakingChanges',
        type: 'boolean',
        description:
          'Explicitly allow breaking changes (e.g. adding mandatory parameter, removing export) if intentional.',
      },
    ],
    notes: ['Mutating and confirmation-gated.'],
  },
  'codebase-invariant-check': {
    longDescription:
      'Compare candidate code with its original source and report structural invariants that may have changed. Use before writing a risky refactor; it validates but does not modify files.',
    params: [
      {
        name: 'file',
        type: 'string',
        description: 'Path to existing source file to compare against candidate modifications.',
      },
      {
        name: 'originalCode',
        type: 'string',
        description: 'Original source code string (if not reading from an existing file).',
      },
      {
        name: 'modifiedCode',
        type: 'string',
        required: true,
        description: 'The candidate modified code string to validate.',
      },
      {
        name: 'lang',
        type: 'string',
        description: 'Language hint (ts, py, go, rs, etc.). Inferred from file path if omitted.',
      },
    ],
    notes: ['Read-only. Use before applying a breaking signature change.'],
  },
  'codebase-impact-analysis': {
    longDescription:
      'Find likely callers, dependents, related tests, and change risk for a named symbol. Use it before changing a public or widely used declaration.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/class/type name to analyze.',
      },
      {
        name: 'file',
        type: 'string',
        description:
          'Optional file path to disambiguate when multiple symbols share the same name.',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'Whether to traverse transitive callers (callers of callers). Defaults to true.',
      },
    ],
    notes: ['Run before changing public signatures, then pair with codebase-targeted-test.'],
  },
  'codebase-targeted-test': {
    longDescription:
      'Discover and run tests that cover a specified symbol, source file, or explicit test files. Use it for focused regression validation after a change.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        description: 'Symbol name whose covering tests should be discovered and run.',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Source file path whose covering tests should be run.',
      },
      {
        name: 'testFiles',
        type: 'string[]',
        description: 'Explicit list of test files to execute.',
      },
    ],
    notes: ['Execution is confirmation-gated even though it does not edit files.'],
  },
  'security-ast-scan': {
    longDescription:
      'Statically scan source code for supported security patterns and return findings with locations. Use it as a focused code check, not as a substitute for a full security assessment.',
    params: [
      {
        name: 'file',
        type: 'string',
        description: 'File path to scan (relative to project root).',
      },
      {
        name: 'content',
        type: 'string',
        description: 'Direct code string to scan without writing to disk.',
      },
      {
        name: 'rules',
        type: 'string[]',
        description: 'Optional list of rule IDs to filter by.',
      },
    ],
    notes: ['Returns severity-ranked findings with line numbers and remediation guidance.'],
  },
  'codebase-incoming-calls': {
    longDescription:
      'Find indexed call sites that invoke a named function, method, or type, optionally scoped to a file. Use it to estimate breakage before changing an API.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/type name to find callers for',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Scope to a specific file when multiple symbols share the same name',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum call sites to return (default 50, max 200)',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'When true, traverse the full transitive call chain (callers of callers, to unlimited depth). Default false: return only direct callers. Cycle-safe via SQL recursive CTE.',
      },
    ],
  },
  'codebase-outgoing-calls': {
    longDescription:
      'Find indexed symbols called by a named function, method, or type, optionally scoped to a file. Use it to understand dependencies before refactoring behavior.',
    params: [
      {
        name: 'symbol',
        type: 'string',
        required: true,
        description: 'The function/method/type name to find callees for',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Scope to a specific file when multiple symbols share the same name',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum call sites to return (default 50, max 200)',
      },
      {
        name: 'transitive',
        type: 'boolean',
        description:
          'When true, traverse the full transitive dependency chain (callees of callees, to unlimited depth). Default false: return only direct callees. Cycle-safe via SQL recursive CTE.',
      },
    ],
  },
  'codebase-stats': {
    longDescription:
      'Report codebase-index health, indexed file and symbol counts, languages, and freshness. Use it before relying on indexed discovery results.',
    params: [],
    notes: [
      'Use to see if the index is up-to-date or needs a refresh.',
      'No arguments required.',
      'Helps avoid wasting tokens on searches against a stale index.',
    ],
  },
  'dead-code-scan': {
    longDescription:
      'Find dead code in executable TS/JS sources: unreachable files, exports nothing imports, unused re-exports, test-only code and unused dependencies. Read-only; pass previewIds to see the exact cleanup diff.',
    params: [
      {
        name: 'paths',
        type: 'string[]',
        description: 'Project-relative path prefixes to report on.',
      },
      {
        name: 'categories',
        type: "Array<'unreachable-file' | 'test-only-file' | 'dead-export' | 'unused-export' | 'unused-reexport' | 'test-only-export' | 'unused-local' | 'unused-dependency' | 'unused-public-export'>",
        description: 'Only these categories.',
      },
      {
        name: 'minConfidence',
        type: "'high' | 'medium' | 'low'",
        description: 'Lowest confidence to list (default low).',
      },
      {
        name: 'includePublicApi',
        type: 'boolean',
        description: 'Also report published-package API that nothing in the repo imports.',
      },
      {
        name: 'entries',
        type: 'string[]',
        description: 'Extra entry files/globs loaded outside the import graph.',
      },
      {
        name: 'limit',
        type: 'number',
        description: 'Max findings listed (default 100).',
      },
      {
        name: 'previewIds',
        type: 'string[]',
        description: 'Finding ids to preview as a diff (no writes).',
      },
    ],
    notes: [
      'Read-only (permission: auto, mutating: false). Results are best-effort — dynamic imports, string-based require, and bare `export { X }` re-exports without a local function wrapper create no reference edge and may appear as false dead-code positives.',
      'Entry-point discovery handles root + workspace packages, including pnpm-workspace.yaml packages block and build-output/bin entries mapped back to source.',
    ],
  },
  present_artifact: {
    longDescription:
      'Present an existing project text file, raster image, unified diff, or an owned live browser session. Graphical surfaces use read-only previews or their file viewer. The request is scoped to the current session and does not change contents.',
    params: [
      {
        name: 'browserSessionId',
        type: 'string',
        description: 'Existing live browser session opened by this agent in this conversation.',
      },
      {
        name: 'path',
        type: 'string',
        description: 'Existing file relative to the project root.',
      },
      {
        name: 'title',
        type: 'string',
        description: 'Short label for the result.',
      },
    ],
  },
  'dead-code-fix': {
    longDescription:
      'Remove dead code by dead-code-scan finding id: re-scans, applies, typechecks, rolls back on failure and keeps an undo backup. Only for ids the user chose after reviewing the scan.',
    params: [
      {
        name: 'action',
        type: "'apply' | 'undo' | 'backups'",
        required: true,
        description:
          'apply = remove the given finding ids; undo = restore a backup; backups = list them.',
      },
      {
        name: 'ids',
        type: 'string[]',
        description: 'Finding ids from dead-code-scan (apply).',
      },
      {
        name: 'verify',
        type: "'typecheck' | 'none'",
        description: 'Post-apply verification (default typecheck).',
      },
      {
        name: 'backupId',
        type: 'string',
        description: 'Backup to restore (undo).',
      },
      {
        name: 'force',
        type: 'boolean',
        description: 'Undo even over files edited after the fix.',
      },
    ],
  },
};
