// Per-tool detail data for the built-in tool detail pages.
// Generated by scripts/generate-website-tool-catalog.ts from @wrongstack/tools.
// Run `pnpm website:tools:write` after changing a built-in tool contract.

import type { ToolDetail } from './tool-detail-types';

export const toolDetailsPart2: Record<string, ToolDetail> = {
  read: {
    longDescription:
      'Read a project file safely, with optional line ranges and binary-aware output. Use it to inspect source before editing; paths must stay within the project.',
    params: [
      {
        name: 'path',
        type: 'string',
        required: true,
        description: 'Path to the file (relative to project root or absolute within project).',
      },
      {
        name: 'offset',
        type: 'integer',
        description: '1-based starting line number. Use together with `limit` for large files.',
      },
      {
        name: 'limit',
        type: 'integer',
        description:
          'Maximum number of lines to return (default 2000). Values above 5000 are clamped to 5000 — page with `offset` for more.',
      },
      {
        name: 'mode',
        type: "'content' | 'summary'",
        description:
          'Return full line-numbered content (default) or a compact file summary with imports/exports/symbols.',
      },
      {
        name: 'includeSymbols',
        type: 'boolean',
        description:
          'When true, include the codebase-index symbol list for this file as a structured `symbols` field in the result. Overrides the advanced-mode meta flag per-call.',
      },
    ],
    doNotUseWhen: ['you need to search many files for matching content.'],
    useInstead: ['grep'],
    notes: [
      'Always read a file before using `edit`, `replace`, or `write` on it (the system often requires it for safety).',
      'Use `offset` + `limit` for very large files instead of reading everything at once.',
      'Default limit is generous (2000 lines) but can be increased.',
      'Output is capped at 256 KiB.',
    ],
  },
  read_url_content: {
    longDescription:
      'Fetch content from a URL via HTTP request and convert HTML directly to clean markdown. Use for public docs and web pages without browser overhead.',
    params: [
      {
        name: 'url',
        type: 'string',
        description: 'URL to read content from.',
      },
      {
        name: 'Url',
        type: 'string',
        description: 'Case-tolerant alias for URL.',
      },
      {
        name: 'maxBytes',
        type: 'number',
        description: 'Maximum bytes to retrieve (default: 128KB, max 1MB).',
      },
    ],
    notes: [
      'Use for static pages, documentation and text extraction where visual interaction is unnecessary.',
      'No JavaScript execution or authenticated browser session is available.',
      'Interactive, login-gated or visually inspected pages belong in the browser tools.',
    ],
  },
  write: {
    longDescription:
      'Create or replace one project file with the complete supplied content. Use for new files or intentional full rewrites, after reading existing content when applicable.',
    params: [
      {
        name: 'path',
        type: 'string',
        required: true,
        description: 'Relative path from project root. Must not escape the project.',
      },
      {
        name: 'content',
        type: 'string',
        required: true,
        description: 'The complete new content of the file.',
      },
    ],
    doNotUseWhen: ['making a precise change to part of an existing file.'],
    useInstead: ['edit'],
    notes: [
      'Use `write` primarily for new files or when you want to replace the entire content.',
      'For any existing file, strongly prefer `edit` (it requires a prior `read` in the same session and is more precise).',
      'When overwriting an existing file, the tool reads the current content itself to compute the diff — but still `read` the file first before large rewrites so you know what you are replacing.',
      'When overwriting an existing file, the content is normalized to the dominant line-ending style (CRLF/LF) of the existing file; new files are written verbatim.',
    ],
  },
  edit: {
    longDescription:
      'Make a precise, guarded text edit by replacing an expected block in a project file. Prefer it for small source changes so mismatches prevent accidental overwrites.',
    params: [
      {
        name: 'path',
        type: 'string',
        required: true,
        description:
          'Path to the file to edit — relative to the project root, or absolute inside it.',
      },
      {
        name: 'old_string',
        type: 'string',
        required: true,
        description:
          'The exact text to replace, including whitespace and indentation. Must be unique in the file unless `replace_all` is set — add surrounding lines to disambiguate.',
      },
      {
        name: 'new_string',
        type: 'string',
        required: true,
        description: 'The exact replacement text (may be empty to delete `old_string`).',
      },
      {
        name: 'replace_all',
        type: 'boolean',
        description:
          'Replace every occurrence instead of requiring a unique match. Only allowed when `old_string` matches exactly (or up to trailing whitespace) — fuzzy matches stay single-target.',
      },
    ],
    doNotUseWhen: [
      'creating a new file, replacing the whole file, or applying an existing unified diff.',
    ],
    useInstead: ['write', 'patch'],
    notes: [
      'Prefer calling `read` on the target file first when planning an edit.',
      'Use a sufficiently unique `old_string` (include surrounding lines/context if needed).',
      'If the string appears multiple times and you want to change all of them, set `replace_all: true`.',
    ],
  },
  replace: {
    longDescription:
      'Preview or apply a regular-expression replacement across selected project files. Start with dry_run, constrain files and globs carefully, then apply only reviewed changes.',
    params: [
      {
        name: 'pattern',
        type: 'string',
        required: true,
        description: 'Regex pattern to match',
      },
      {
        name: 'replacement',
        type: 'string',
        required: true,
        description:
          'Replacement string. Supports `$1`–`$9` (capture groups), `$&` (whole match), and `$$` (literal dollar sign) — same semantics as JavaScript String.replace.',
      },
      {
        name: 'files',
        type: 'string',
        required: true,
        description: 'File(s) to target: single path, comma-separated list, or glob pattern',
      },
      {
        name: 'glob',
        type: 'string',
        description: 'Additional glob filter (e.g. "*.ts")',
      },
      {
        name: 'replace_all',
        type: 'boolean',
        description: 'Replace all occurrences in each file (default: true)',
      },
      {
        name: 'dry_run',
        type: 'boolean',
        description: 'Preview changes without writing (default: true)',
      },
    ],
    notes: [
      'Run without `dry_run: false` first to see exactly what would change (dry-run is the default).',
      'Review the diff output, then re-run with `dry_run: false` to apply.',
      'Use a specific enough `pattern` (and `glob` / `files`) to avoid accidental broad changes.',
    ],
  },
  glob: {
    longDescription:
      'Find project files by glob pattern, respecting repository boundaries and ignore rules. Use it to locate candidate paths before reading or editing them.',
    params: [
      {
        name: 'pattern',
        type: 'string',
        required: true,
        description: 'Glob pattern to match (e.g. "**/*.ts", "src/**").',
      },
      {
        name: 'path',
        type: 'string',
        description: 'Base directory to search from (defaults to project root).',
      },
      {
        name: 'limit',
        type: 'integer',
        description:
          'Maximum number of results to return (default 1000, max 5000). Results are sorted by mtime descending, so truncation keeps the most recently modified files.',
      },
    ],
    doNotUseWhen: ['you need to search inside file contents.'],
    useInstead: ['grep'],
    notes: [
      'Use early to get a list of files you actually care about.',
      'Combine with `path` and `limit`.',
      'Default ignores common build/dependency directories.',
      'Output is capped at 64 KiB.',
    ],
  },
  grep: {
    longDescription:
      'Search project text with a bounded regular expression and contextual matches. Use it for exact literals or patterns when semantic codebase search is not appropriate.',
    params: [
      {
        name: 'pattern',
        type: 'string',
        required: true,
        description: 'Regular expression pattern to search for in file contents.',
      },
      {
        name: 'path',
        type: 'string',
        description: 'Limit search to this directory or file (relative to project root).',
      },
      {
        name: 'glob',
        type: 'string',
        description: 'Glob filter for which files to include (e.g. "**/*.ts", "src/**").',
      },
      {
        name: 'output_mode',
        type: "'content' | 'files_with_matches' | 'count'",
        description: 'Return style: detailed matches, just file list, or count only.',
      },
      {
        name: 'context_lines',
        type: 'integer',
        description: 'How many lines of surrounding context to include with each match.',
      },
      {
        name: 'case_insensitive',
        type: 'boolean',
        description: 'Ignore case when matching.',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Maximum number of matches to return.',
      },
    ],
    doNotUseWhen: ['you only need to locate files by name or path pattern.'],
    useInstead: ['glob'],
    notes: [
      '`pattern` is a regular expression.',
      'Use `output_mode: "content"` (default) to get matching lines with context.',
      'Use `"files_with_matches"` when you only need the list of files.',
      'Output is capped at 128 KiB.',
    ],
  },
  bash: {
    longDescription:
      'Run a shell command in the project with bounded output and timeout controls. Use it for development commands after checking side effects; background mode returns a process handle.',
    params: [
      {
        name: 'command',
        type: 'string',
        required: true,
        description: 'The exact shell command to run. Prefer simple, focused commands.',
      },
      {
        name: 'timeout_ms',
        type: 'integer',
        description:
          'Optional timeout for this specific command in milliseconds (default 300000, max 600000).',
      },
      {
        name: 'background',
        type: 'boolean',
        description:
          'If true, launch the process in the background and return the PID immediately.',
      },
    ],
    doNotUseWhen: [
      'the command is allowlisted and does not require pipes, redirection, or shell expansion.',
    ],
    useInstead: ['exec'],
    notes: [
      'Strongly prefer `exec` for known safe commands (node, npm, pnpm, tsc, git, etc.).',
      'Use bash only when you genuinely need shell features (pipes, redirection, complex one-liners).',
      'Prefer single focused commands over huge `&&` chains.',
      'Output is capped at 32 KiB.',
    ],
  },
  exec: {
    longDescription:
      'Execute a command directly without shell interpretation, using explicit program arguments. Prefer it when argument safety and predictable process invocation matter.',
    params: [
      {
        name: 'command',
        type: 'string',
        required: true,
        description:
          'The base command to run. Must be in the internal allowlist (e.g. "node", "pnpm", "git", "tsc").',
      },
      {
        name: 'args',
        type: 'string[]',
        description: 'Arguments passed to the command. Passed as an array (no shell parsing).',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Optional working directory. Must resolve inside the project root.',
      },
      {
        name: 'timeout',
        type: 'integer',
        description: 'Per-command timeout in milliseconds (default 30000, max 600000).',
      },
    ],
    doNotUseWhen: [
      'the operation requires pipes, redirection, shell expansion, or a non-allowlisted command.',
    ],
    useInstead: ['bash'],
    notes: [
      '`command` must be in the allowlist. Defaults cover JS (node/npm/pnpm/yarn/bun/deno/tsc/vitest/eslint/biome), Go (`go build`/`go test`), Rust (cargo), Python (python/pip), Ruby (gem/bundle), JVM (java/mvn/gradle), .NET (dotnet), native (make/cmake), and git. Users can extend it via `tools.exec.allow` in config.',
      'Arguments are passed as a clean array (no shell interpretation).',
      '`cwd` is validated to stay inside the project.',
    ],
  },
  pwsh: {
    longDescription:
      'Execute a PowerShell command in the project with timeout, output, and background controls. Use it for Windows-native project operations and verify commands that can modify state.',
    params: [
      {
        name: 'command',
        type: 'string',
        required: true,
        description: 'The exact PowerShell command or script block to run.',
      },
      {
        name: 'workdir',
        type: 'string',
        description:
          'Absolute or project-relative path to the working directory for this command. Defaults to session working directory.',
      },
      {
        name: 'timeout_ms',
        type: 'integer',
        description:
          'Optional timeout for this specific command in milliseconds (default 300000, max 600000).',
      },
      {
        name: 'run_in_background',
        type: 'boolean',
        description:
          'If true, launch the process in the background and return the job ID / PID immediately.',
      },
      {
        name: 'background',
        type: 'boolean',
        description: 'Alias for run_in_background.',
      },
    ],
    doNotUseWhen: [
      'the command is an allowlisted single binary (node, git, pnpm, tsc) needing no shell expansion or pipelines.',
    ],
    useInstead: ['exec'],
    notes: [
      'Stateless: No cwd, variables, or functions persist between calls. Use `workdir` to set the directory.',
      'Paths & Environs: Use native Windows paths (`C:\\...`) and read env vars via `$env:NAME` (and `$env:DSH_*`).',
      'Sandboxing: Under read-only sandbox, pwsh runs in `ConstrainedLanguage` mode. Workspace-write runs in `FullLanguage`.',
      'Background: Set `run_in_background: true` for long-running processes (returns job id; manage via job_output/job_kill).',
      'Output is capped at 32 KiB.',
    ],
  },
  fetch: {
    longDescription:
      'Fetch and extract content from an approved HTTP(S) URL for research or integration work. Use it for a known page or endpoint, not for general web discovery.',
    params: [
      {
        name: 'url',
        type: 'string',
        required: true,
        description: 'The target URL (must use https://).',
      },
      {
        name: 'format',
        type: "'markdown' | 'text' | 'raw'",
        description:
          'Output format. "markdown" (default for HTML) converts HTML to Markdown; "text" strips HTML to plain text; "raw" returns the body unmodified. JSON is pretty-printed except in raw.',
      },
    ],
    notes: [
      'Only HTTPS is allowed by default.',
      'Internal/private networks are blocked unless explicitly enabled via environment variable.',
      'Redirects are followed but re-validated at each hop.',
      'Output is capped at 128 KiB.',
    ],
  },
  search: {
    longDescription:
      'Search the public web for current external information, then inspect selected results with fetch. Use it when repository evidence is insufficient or the fact may have changed.',
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: 'Search query',
      },
      {
        name: 'num_results',
        type: 'integer',
        description: 'Number of results (1-50, default 10)',
      },
      {
        name: 'source',
        type: "'duckduckgo' | 'google' | 'bing'",
        description: 'Search engine to use (default: duckduckgo)',
      },
      {
        name: 'skip_cache',
        type: 'boolean',
        description: 'Skip the in-memory cache and force a fresh search (default: false)',
      },
    ],
    notes: [
      'Prefer specific queries over very broad ones.',
      'Results go through the guarded fetch system (same protections as the `fetch` tool).',
      'Supports duckduckgo (default), google, and bing sources.',
    ],
  },
  todo: {
    longDescription:
      'Create, update, or list the session’s concrete work items and their progress. Use it to keep multi-step work visible; it does not implement the tasks itself.',
    params: [
      {
        name: 'todos',
        type: 'object[]',
        required: true,
        description:
          'The desired todo list. Supplied rows are replaced/reordered; unfinished omitted rows are retained.',
      },
    ],
    notes: [
      'At the beginning of a non-trivial task, create a clear todo list with specific, actionable items.',
      'Only one item should be `in_progress` at any time.',
      'Update the list frequently as work progresses (mark items done, add new ones, change status).',
    ],
  },
  plan: {
    longDescription:
      'Create and manage higher-level plan-board items, priorities, and status. Use it for strategic work tracking rather than small immediate edits.',
    params: [
      {
        name: 'action',
        type: "'show' | 'add' | 'status' | 'start' | 'done' | 'remove' | 'promote' | 'template_use' | 'clear' | 'taskify'",
        required: true,
        description: 'The operation to perform on the plan board.',
      },
      {
        name: 'title',
        type: 'string',
        description: 'Title of the plan item. Required for action=add.',
      },
      {
        name: 'details',
        type: 'string',
        description: 'Additional details or description for a new plan item (action=add).',
      },
      {
        name: 'target',
        type: 'string',
        description:
          'Identifier for the target plan item (id, 1-based index, or partial title). Required for most actions except add/show/clear.',
      },
      {
        name: 'status',
        type: "'open' | 'in_progress' | 'done'",
        description: 'Exact plan item status for action=status.',
      },
      {
        name: 'subtasks',
        type: 'string[]',
        description:
          'List of subtask titles. Used with promote to break a plan item into multiple todos.',
      },
      {
        name: 'template',
        type: 'string',
        description:
          'Template identifier when using action=template_use. Common values: new-feature, bug-fix, refactor, release, security-audit.',
      },
      {
        name: 'scope',
        type: "'session' | 'project'",
        description:
          'Storage scope: "session" (default, isolated to this session) or "project" (shared across all sessions for this project).',
      },
    ],
    notes: [
      'Start by creating a high-level plan with `action: "add"` or using templates (`template_use`).',
      'Use `promote` to turn a plan item into actionable todos.',
      'Use `taskify` to convert a plan item into a structured task (with type/priority/deps).',
    ],
  },
  kanban: {
    longDescription:
      'Manage project Kanban boards, cards, assignments, and acceptance evidence. Use it for persistent team workflow; changing board state is intentional and reviewable.',
    params: [
      {
        name: 'action',
        type: "'list_boards' | 'get_board' | 'create_board' | 'duplicate_board' | 'update_board' | 'adopt_managed_lifecycle' | 'release_managed_lifecycle' | 'delete_board' | 'generate_board' | 'export_markdown' | 'export_task_graph' | 'sync_task_graph' | 'create_from_graph' | 'import_session_tasks' | 'search_tasks' | 'ready_tasks' | 'snapshot' | 'workbench' | 'add_task' | 'split_task' | 'merge_tasks' | 'copy_task' | 'transfer_task' | 'get_task' | 'start_task' | 'update_task' | 'transition_task' | 'repair_managed_projection' | 'move_task' | 'delete_task' | 'set_chain' | 'get_chain' | 'claim_task' | 'release_task' | 'assign_task' | 'mark_assignment' | 'heartbeat_assignment' | 'recover_stale' | 'events' | 'board_history' | 'record_activity' | 'queue_health' | 'add_dependency' | 'add_goal_metric' | 'update_goal_metric' | 'add_check' | 'update_check' | 'remove_check' | 'add_note' | 'review_task' | 'add_link' | 'verify_completion' | 'split_atomic' | 'assess_atomicity' | 'propose_decomposition' | 'approve_decomposition' | 'reject_decomposition' | 'get_contract_graph' | 'configure_contract_graph' | 'upsert_contract_node' | 'remove_contract_node' | 'add_contract_edge' | 'remove_contract_edge'",
        required: true,
        description:
          'Operation to perform. Choose an action first; supply only the fields that action needs.',
      },
      {
        name: 'boardId',
        type: 'string',
        description: 'Target board identifier, returned by list_boards or create_board.',
      },
      {
        name: 'taskId',
        type: 'string',
        description: 'Target card identifier, returned by add_task, get_board, or search_tasks.',
      },
      {
        name: 'reviewDisposition',
        type: "'adequate' | 'enriched' | 'needs_leader'",
        description:
          'review_task: record the background manager assessment after inspecting this card; note supplies the reason. Does not complete product work.',
      },
      {
        name: 'taskIds',
        type: 'string[]',
        description: 'Card identifiers for a bulk, merge, chain, or transfer action.',
      },
      {
        name: 'chainId',
        type: 'string',
        description: 'Identifier for the chain used by the selected action.',
      },
      {
        name: 'columnId',
        type: 'string',
        description: 'Identifier for the column used by the selected action.',
      },
      {
        name: 'targetBoardId',
        type: 'string',
        description: 'Identifier for the target board used by the selected action.',
      },
      {
        name: 'targetColumnId',
        type: 'string',
        description: 'Identifier for the target column used by the selected action.',
      },
      {
        name: 'title',
        type: 'string',
        description: 'Human-readable board or card title.',
      },
      {
        name: 'description',
        type: 'string',
        description: 'Detailed board or card scope, expected outcome, or implementation context.',
      },
      {
        name: 'dueDate',
        type: 'string',
        description: 'Optional due date recorded on the card.',
      },
      {
        name: 'tags',
        type: 'string[]',
        description: 'Free-form tags applied to a card or used to filter a result.',
      },
      {
        name: 'labels',
        type: 'string[]',
        description: 'Labels applied to a card or used to filter results.',
      },
      {
        name: 'label',
        type: 'string',
        description:
          'search_tasks / ready_tasks / snapshot: filter by a single label (takes precedence over labels[0]).',
      },
      {
        name: 'priority',
        type: "'critical' | 'high' | 'medium' | 'low'",
        description: 'Card priority used when creating or updating work.',
      },
      {
        name: 'taskType',
        type: "'feature' | 'bugfix' | 'refactor' | 'docs' | 'test' | 'chore'",
        description:
          'Optional task type value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'status',
        type: "'pending' | 'ready' | 'in_progress' | 'blocked' | 'review' | 'completed' | 'failed' | 'archived'",
        description: 'Card status to set or filter by for the selected action.',
      },
      {
        name: 'order',
        type: 'number',
        description:
          'Optional order value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'query',
        type: 'string',
        description: 'Text query used by search_tasks or a generation/decomposition action.',
      },
      {
        name: 'limit',
        type: 'number',
        description:
          'ready_tasks: max results. workbench: per-lane and alert limit. events: return only the most recent N events.',
      },
      {
        name: 'agentId',
        type: 'string',
        description: 'Stable agent identifier for an assignment, lease, or activity.',
      },
      {
        name: 'name',
        type: 'string',
        description:
          'Optional name value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'role',
        type: 'string',
        description:
          'Optional role value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'provider',
        type: 'string',
        description:
          'Optional provider value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'model',
        type: 'string',
        description:
          'Optional model value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'fallbackProfile',
        type: 'string',
        description:
          'Optional fallback profile value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'fallbackModels',
        type: 'string[]',
        description:
          'Optional fallback models value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'tools',
        type: 'string[]',
        description:
          'Optional tools value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'allowedCapabilities',
        type: 'string[]',
        description:
          'Optional allowed capabilities value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'leaseId',
        type: 'string',
        description: 'Lease token returned by claim_task; required by lease-protected updates.',
      },
      {
        name: 'claimedAt',
        type: 'string',
        description:
          'Optional claimed at value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'heartbeatAt',
        type: 'string',
        description:
          'Optional heartbeat at value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'leaseExpiresAt',
        type: 'string',
        description:
          'Optional lease expires at value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'attempt',
        type: 'number',
        description:
          'Optional attempt value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'maxAttempts',
        type: 'number',
        description:
          'Optional max attempts value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'subagentId',
        type: 'string',
        description: 'Identifier for the subagent used by the selected action.',
      },
      {
        name: 'runTaskId',
        type: 'string',
        description: 'Identifier for the run task used by the selected action.',
      },
      {
        name: 'lastResult',
        type: 'string',
        description:
          'Optional last result value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'error',
        type: 'string',
        description:
          'Optional error value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'expectedLeaseId',
        type: 'string',
        description:
          'Fence token expected by a mutation; prevents a stale worker from overwriting newer work.',
      },
      {
        name: 'assignmentStatus',
        type: "'assigned' | 'queued' | 'running' | 'completed' | 'failed' | 'cancelled'",
        description:
          'Optional assignment status value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'lifecycleStage',
        type: "'backlog' | 'todo' | 'running' | 'review' | 'done'",
        description:
          'Optional lifecycle stage value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'transitionAction',
        type: 'string',
        description:
          'Optional transition action value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'transitionComment',
        type: 'string',
        description:
          'Optional transition comment value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'tickChecks',
        type: 'object[]',
        description:
          '`transition_task` with lifecycleStage "done" only (rejected for any other stage): flip one or more manual criteria before the gate fires. Read ids from kanban get_task. Non-manual criteria are refused.',
      },
      {
        name: 'attachmentUrl',
        type: 'string',
        description: 'URL or project reference attached to the card.',
      },
      {
        name: 'attachmentTitle',
        type: 'string',
        description: 'Human-readable title for the attached reference.',
      },
      {
        name: 'attachmentType',
        type: "'issue' | 'pr' | 'doc' | 'commit' | 'design' | 'file' | 'url' | 'other'",
        description:
          'Optional attachment type value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'releaseStatus',
        type: "'pending' | 'ready' | 'blocked'",
        description:
          'Optional release status value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'releaseReason',
        type: 'string',
        description:
          'Optional release reason value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'clearAssignee',
        type: 'boolean',
        description:
          'Optional clear assignee value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryMode',
        type: "'auto' | 'release' | 'retry' | 'fail'",
        description:
          'Optional recovery mode value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryNow',
        type: 'string',
        description:
          'Optional recovery now value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryPolicyFailOnCostCeiling',
        type: 'boolean',
        description:
          'Optional recovery policy fail on cost ceiling value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryPolicyReleaseOnFailureKinds',
        type: 'string[]',
        description:
          'Optional recovery policy release on failure kinds value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryPolicyReleaseOnHeartbeatDue',
        type: 'boolean',
        description:
          'Optional recovery policy release on heartbeat due value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'recoveryPolicyRetryPolicyOverride',
        type: "'off' | 'incremental' | 'exponential'",
        description:
          'Optional recovery policy retry policy override value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'assignee',
        type: 'string',
        description: 'Agent or person assigned to own this card.',
      },
      {
        name: 'costCeilingUsd',
        type: 'number',
        description:
          'Optional cost ceiling usd value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'retryPolicy',
        type: "'off' | 'incremental' | 'exponential'",
        description:
          'Optional retry policy value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'lastFailureKind',
        type: 'string',
        description:
          'Optional last failure kind value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'dependsOn',
        type: 'string[]',
        description:
          'Task ids this card waits on. On update_task an explicit empty array clears them — use it when a dependency was recorded in error rather than completing work nobody wants.',
      },
      {
        name: 'atomic',
        type: 'boolean',
        description:
          'Composite parent (true) or executable leaf (false). Set false to make a stranded parent a leaf again after its children were dropped.',
      },
      {
        name: 'childTaskIds',
        type: 'string[]',
        description:
          'Children of a composite parent. On update_task an explicit empty array detaches them all.',
      },
      {
        name: 'estimatedHours',
        type: 'number',
        description:
          'Optional estimated hours value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'actualHours',
        type: 'number',
        description:
          'Optional actual hours value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'taskGraph',
        type: 'object',
        description: 'Structured task graph to import, synchronize, or materialize.',
      },
      {
        name: 'graphId',
        type: 'string',
        description: 'Identifier for the graph used by the selected action.',
      },
      {
        name: 'specId',
        type: 'string',
        description: 'Identifier for the spec used by the selected action.',
      },
      {
        name: 'specRequirementId',
        type: 'string',
        description: 'Identifier for the spec requirement used by the selected action.',
      },
      {
        name: 'sourceSystem',
        type: 'string',
        description: 'External system that produced an imported task graph.',
      },
      {
        name: 'phaseId',
        type: 'string',
        description: 'Identifier for the phase used by the selected action.',
      },
      {
        name: 'preserveOriginTaskIds',
        type: 'boolean',
        description: 'Whether the selected action should preserve origin task ids.',
      },
      {
        name: 'includeArchived',
        type: 'boolean',
        description: 'Whether the selected action should include archived.',
      },
      {
        name: 'archiveMissingTasks',
        type: 'boolean',
        description:
          'Optional archive missing tasks value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'preserveManualDependencies',
        type: 'boolean',
        description: 'Whether the selected action should preserve manual dependencies.',
      },
      {
        name: 'dependencyTaskId',
        type: 'string',
        description: 'Identifier for the dependency task used by the selected action.',
      },
      {
        name: 'enforceDependencies',
        type: 'boolean',
        description:
          'Optional enforce dependencies value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'childTitles',
        type: 'string[]',
        description: 'Titles used by split_task to create child cards.',
      },
      {
        name: 'inheritAssignment',
        type: 'boolean',
        description: 'Whether the selected action should inherit assignment.',
      },
      {
        name: 'inheritLabels',
        type: 'boolean',
        description: 'Whether the selected action should inherit labels.',
      },
      {
        name: 'inheritSuccessCriteria',
        type: 'boolean',
        description: 'Whether the selected action should inherit success criteria.',
      },
      {
        name: 'inheritGoalMetrics',
        type: 'boolean',
        description: 'Whether the selected action should inherit goal metrics.',
      },
      {
        name: 'inheritDependencies',
        type: 'boolean',
        description: 'Whether the selected action should inherit dependencies.',
      },
      {
        name: 'chainChildren',
        type: 'boolean',
        description:
          'Optional chain children value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'rewireDependents',
        type: 'boolean',
        description:
          'Optional rewire dependents value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'closeSourceTasks',
        type: 'boolean',
        description:
          'Optional close source tasks value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'metricId',
        type: 'string',
        description: 'Goal-metric identifier returned by get_task.',
      },
      {
        name: 'metricName',
        type: 'string',
        description: 'Display name for a new goal metric.',
      },
      {
        name: 'metricTarget',
        type: 'string | number',
        description: 'Desired goal-metric value.',
      },
      {
        name: 'metricCurrent',
        type: 'string | number',
        description: 'Observed goal-metric value used for verification.',
      },
      {
        name: 'metricDirection',
        type: "'at_least' | 'at_most'",
        description:
          'Optional metric direction value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'metricUnit',
        type: 'string',
        description:
          'Optional metric unit value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'metricStatus',
        type: "'pending' | 'met' | 'missed' | 'waived'",
        description:
          'Optional metric status value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'metricNotes',
        type: 'string',
        description:
          'Optional metric notes value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'checkId',
        type: 'string',
        description: 'Acceptance-criterion identifier returned by get_task.',
      },
      {
        name: 'checkDescription',
        type: 'string',
        description: 'Acceptance criterion to add or update on the card.',
      },
      {
        name: 'checkStatus',
        type: "'pending' | 'passed' | 'failed' | 'skipped'",
        description: 'Current outcome of an acceptance criterion.',
      },
      {
        name: 'checkType',
        type: "'manual' | 'command' | 'test' | 'file_exists' | 'file_matches' | 'git_diff' | 'metric'",
        description:
          'How this acceptance criterion is verified. Default "manual" (status set by hand). Any other value makes verify_completion execute it, so the criterion becomes real evidence rather than a self-assertion. Pair with checkNotes.',
      },
      {
        name: 'checkNotes',
        type: 'string',
        description:
          'The executable body for a non-manual checkType, read in preference to checkDescription. command/test: the shell command or test pattern. file_exists: the path. file_matches: JSON {"file","pattern","flags"}. git_diff: JSON {"expectedFiles","minChanges","maxChanges"}.',
      },
      {
        name: 'contractEnforcement',
        type: "'off' | 'advisory' | 'strict'",
        description:
          'Board-level contract map enforcement. Default when first configured: advisory.',
      },
      {
        name: 'contractNodeId',
        type: 'string',
        description: 'Identifier for the contract node used by the selected action.',
      },
      {
        name: 'contractNodeKind',
        type: "'objective' | 'guardrail' | 'risk' | 'component' | 'artifact' | 'verification'",
        description:
          'objective = what this card is for; guardrail = what must keep working; risk = what could go wrong; component/artifact = what it touches; verification = what settles it.',
      },
      {
        name: 'contractNodeTitle',
        type: 'string',
        description:
          'Optional contract node title value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractNodeDescription',
        type: 'string',
        description:
          'Optional contract node description value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractNodeState',
        type: "'unknown' | 'active' | 'satisfied' | 'violated' | 'waived' | 'resolved'",
        description:
          'Optional contract node state value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractNodeEnforcement',
        type: "'blocking' | 'advisory' | 'informational'",
        description:
          'Optional contract node enforcement value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractCheckId',
        type: 'string',
        description: 'Identifier for the contract check used by the selected action.',
      },
      {
        name: 'contractMetricId',
        type: 'string',
        description: 'Identifier for the contract metric used by the selected action.',
      },
      {
        name: 'contractWaiverReason',
        type: 'string',
        description: 'Required, with an actor, when contractNodeState is "waived".',
      },
      {
        name: 'contractEdgeId',
        type: 'string',
        description: 'Identifier for the contract edge used by the selected action.',
      },
      {
        name: 'contractEdgeFrom',
        type: 'string',
        description:
          'A contract node id, or a task id (bare or "task:<id>") for the card endpoint.',
      },
      {
        name: 'contractEdgeTo',
        type: 'string',
        description:
          'Optional contract edge to value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractEdgeType',
        type: "'targets' | 'affects' | 'must_preserve' | 'exposes' | 'verified_by' | 'conflicts_with' | 'derived_from' | 'relates_to'",
        description:
          'Optional contract edge type value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'contractEdgeRationale',
        type: 'string',
        description:
          'Optional contract edge rationale value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'note',
        type: 'string',
        description:
          'Human-readable rationale, progress note, review evidence, or activity summary.',
      },
      {
        name: 'activityKind',
        type: "'decision' | 'attempt' | 'result' | 'blocker' | 'observation'",
        description:
          'record_activity: what happened. The summary goes in `note`; `activityDetails` carries any longer body.',
      },
      {
        name: 'activityOutcome',
        type: "'succeeded' | 'failed' | 'partial' | 'skipped' | 'unknown'",
        description:
          'Optional activity outcome value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'activityDetails',
        type: 'string',
        description:
          'Optional activity details value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'author',
        type: 'string',
        description: 'Actor recording the note, activity, check, or review.',
      },
      {
        name: 'url',
        type: 'string',
        description:
          'Optional url value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'linkTitle',
        type: 'string',
        description:
          'Optional link title value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'linkType',
        type: "'issue' | 'pr' | 'doc' | 'commit' | 'design' | 'file' | 'url' | 'other'",
        description:
          'Optional link type value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'context',
        type: 'string',
        description:
          'Optional context value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'columns',
        type: 'string[]',
        description: 'Board column names for create_board or update_board.',
      },
      {
        name: 'generatedBy',
        type: 'string',
        description:
          'Optional generated by value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'includeTasks',
        type: 'boolean',
        description: 'Whether the selected action should include tasks.',
      },
      {
        name: 'includeCompletedTasks',
        type: 'boolean',
        description: 'Whether the selected action should include completed tasks.',
      },
      {
        name: 'preserveAssignment',
        type: 'boolean',
        description: 'Whether the selected action should preserve assignment.',
      },
      {
        name: 'preserveDependencies',
        type: 'boolean',
        description: 'Whether the selected action should preserve dependencies.',
      },
      {
        name: 'atomicityMode',
        type: "'off' | 'assess' | 'enforce'",
        description:
          'Optional atomicity mode value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'atomicityDecomposition',
        type: "'auto' | 'propose'",
        description:
          'Optional atomicity decomposition value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'gateEnforcement',
        type: "'strict' | 'soft'",
        description:
          'Optional gate enforcement value for the selected Kanban action. Supply it only when that action requires it.',
      },
      {
        name: 'proposalId',
        type: 'string',
        description:
          'approve_decomposition / reject_decomposition: the proposal id reported by propose_decomposition.',
      },
      {
        name: 'subtasks',
        type: 'object[]',
        description: 'Proposed child work for decomposition; each item must have a title.',
      },
    ],
    notes: [
      'Use this for durable project kanban state. Agents should call snapshot/ready_tasks, then claim_task before working.',
    ],
  },
  task: {
    longDescription:
      'Manage structured task records, dependencies, ownership, and promotion into actionable session work. Use it to organize bounded work before delegation or execution.',
    params: [
      {
        name: 'action',
        type: "'replace' | 'add' | 'status' | 'show' | 'promote' | 'planify'",
        required: true,
        description:
          'replace = set full list, add = append, status = update task status, show = view only, promote = convert task to todos, planify = convert task to plan item.',
      },
      {
        name: 'tasks',
        type: 'object[]',
        description:
          'Complete desired task list. Existing unfinished tasks may not be omitted; complete them first.',
      },
      {
        name: 'task',
        type: 'object',
        description: 'Single task to append (id/createdAt/updatedAt auto-generated).',
      },
      {
        name: 'id',
        type: 'string',
        description: 'Task id for action=status or target for action=promote.',
      },
      {
        name: 'status',
        type: "'pending' | 'in_progress' | 'blocked' | 'failed' | 'review' | 'completed'",
        description: 'New status for action=status.',
      },
      {
        name: 'target',
        type: 'string',
        description:
          'Target task identifier (id, 1-based index, or title substring) for action=promote.',
      },
      {
        name: 'subtasks',
        type: 'string[]',
        description: 'Optional subtask titles for action=promote. Each becomes a pending todo.',
      },
      {
        name: 'scope',
        type: "'session' | 'project'",
        description:
          'Storage scope: "session" (default, isolated to this session) or "project" (shared across all sessions for this project).',
      },
    ],
    notes: [
      '`action: "replace"` — set the complete task list (tasks ordered by priority)',
      '`action: "status"` — update a task\'s status (e.g. pending→in_progress, in_progress→completed)',
    ],
  },
  git: {
    longDescription:
      'Inspect or run scoped Git operations in the project, including status, diff, history, branches, and commits. Review the target and working tree before mutating operations.',
    params: [
      {
        name: 'command',
        type: "'status' | 'log' | 'diff' | 'commit' | 'branch' | 'checkout' | 'stash' | 'push' | 'pull' | 'fetch' | 'reset' | 'worktree'",
        required: true,
        description: 'Git subcommand',
      },
      {
        name: 'files',
        type: 'string',
        description:
          'File(s) for status/diff: single path, comma-separated list, or "**/*.ts" glob',
      },
      {
        name: 'message',
        type: 'string',
        description: 'Commit message (required for commit)',
      },
      {
        name: 'branch',
        type: 'string',
        description: 'Branch name for checkout/branch',
      },
      {
        name: 'format',
        type: "'short' | 'oneline' | 'stat' | 'graph'",
        description: 'Log format (default: short)',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Limit for log (default: 20)',
      },
      {
        name: 'dry_run',
        type: 'boolean',
        description: 'For commit: show what would be committed',
      },
      {
        name: 'worktreeAction',
        type: "'list' | 'add' | 'remove' | 'prune'",
        description: 'Worktree action: list, add, remove, prune',
      },
      {
        name: 'worktreePath',
        type: 'string',
        description: 'Path for worktree add/remove (e.g. "../wt-feature-xyz")',
      },
      {
        name: 'newBranch',
        type: 'boolean',
        description: 'Create new branch when adding worktree',
      },
      {
        name: 'force',
        type: 'boolean',
        description: 'Force operation (e.g. worktree remove --force)',
      },
    ],
    notes: [
      '`command`: one of the supported subcommands (status, log, diff, commit, etc.)',
      'Use `message` only for commit operations.',
      'Use `files` array for operations that take paths (status, diff, add, etc.).',
    ],
  },
};
