// Per-tool detail data for the built-in tool detail pages.
// Generated by scripts/generate-website-tool-catalog.ts from @wrongstack/tools.
// Run `pnpm website:tools:write` after changing a built-in tool contract.

import type { ToolDetail } from './tool-detail-types';

export const toolDetailsPart1: Record<string, ToolDetail> = {
  browser_open: {
    longDescription:
      'Create an isolated, agent-owned Playwright browser session, optionally opening an approved HTTP(S) URL. Use it to begin browser QA; private and localhost origins require an explicit allowlist.',
    params: [
      {
        name: 'url',
        type: 'string',
        description: 'Optional absolute http(s) URL.',
      },
      {
        name: 'width',
        type: 'integer',
        description: 'Viewport width in CSS pixels; defaults to the browser profile width.',
      },
      {
        name: 'height',
        type: 'integer',
        description: 'Viewport height in CSS pixels; defaults to the browser profile height.',
      },
      {
        name: 'trace',
        type: 'boolean',
        description: 'Capture a Playwright trace; defaults to true.',
      },
    ],
  },
  browser_status: {
    longDescription:
      'Check whether the managed Playwright Chromium installation is available before attempting browser automation.',
    params: [],
  },
  browser_list: {
    longDescription:
      'List browser sessions owned by this agent, including their state and current page, without exposing sessions owned by other agents.',
    params: [],
  },
  browser_navigate: {
    longDescription:
      'Navigate one of this agent’s browser sessions to an approved HTTP(S) URL. Use browser_open first; private and localhost origins require an explicit allowlist.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'url',
        type: 'string',
        required: true,
        description: 'Absolute HTTP(S) URL. Private and localhost origins require an allowlist.',
      },
    ],
  },
  browser_snapshot: {
    longDescription:
      'Inspect the current page through a bounded accessibility snapshot, with redacted console and network summaries. Prefer this before interacting with page elements.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
    ],
  },
  browser_screenshot: {
    longDescription:
      'Capture a PNG of the current page or a selected element for visual QA. The result is a sensitive artifact with integrity metadata.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'fullPage',
        type: 'boolean',
        description: 'Capture the entire scrollable page instead of only the viewport.',
      },
      {
        name: 'selector',
        type: 'string',
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
    ],
  },
  browser_click: {
    longDescription:
      'Click a verified page element in an owned browser session. Snapshot first and use the most specific stable selector available.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        required: true,
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
    ],
  },
  browser_type: {
    longDescription:
      'Fill a form control in an owned browser session. Use secretEnv for credentials so secret values never enter tool arguments or the audit trail.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        required: true,
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
      {
        name: 'text',
        type: 'string',
        description: 'Literal text to enter. Do not use for credentials; use secretEnv instead.',
      },
      {
        name: 'secretEnv',
        type: 'string',
        description: 'Host environment variable resolved only at execution time.',
      },
    ],
  },
  browser_select: {
    longDescription:
      'Choose an option in a select control in an owned browser session after confirming the target selector and intended value.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        required: true,
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
      {
        name: 'value',
        type: 'string',
        required: true,
        description: 'Option value to select from the target select control.',
      },
    ],
  },
  browser_press: {
    longDescription:
      'Send a keyboard key or shortcut to an owned browser session, such as Enter after verifying a form is ready to submit.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'key',
        type: 'string',
        required: true,
        description: 'Keyboard key or shortcut to send, such as Enter or Control+A.',
      },
    ],
  },
  browser_hover: {
    longDescription:
      'Hover over a verified page element in an owned browser session to reveal menus, tooltips, or other hover-driven UI state.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        required: true,
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
    ],
  },
  browser_drag: {
    longDescription:
      'Drag one page element onto another in an owned browser session. Use only when the page’s drag-and-drop interaction is the intended action.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'from',
        type: 'string',
        required: true,
        description: 'Selector for the element to drag.',
      },
      {
        name: 'to',
        type: 'string',
        required: true,
        description: 'Selector for the destination element.',
      },
    ],
  },
  browser_wait: {
    longDescription:
      'Wait for a selector, navigation condition, or bounded duration in an owned browser session before taking the next browser action.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
      {
        name: 'timeoutMs',
        type: 'integer',
        description: 'Maximum wait time in milliseconds, capped at 30 seconds.',
      },
    ],
  },
  browser_evaluate: {
    longDescription:
      'Run a bounded JavaScript expression in an owned page when browser APIs cannot inspect the needed state. Treat page code as arbitrary and use sparingly.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'expression',
        type: 'string',
        required: true,
        description: 'JavaScript expression evaluated in the page; treat page code as arbitrary.',
      },
    ],
  },
  browser_upload: {
    longDescription:
      'Upload project-local files through a page file input in an owned browser session. Verify both the file path and target control before uploading.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
      {
        name: 'selector',
        type: 'string',
        required: true,
        description: 'Stable CSS or supported Playwright selector for the target element.',
      },
      {
        name: 'files',
        type: 'string[]',
        required: true,
        description: 'Project-local file paths to upload through the selected file input.',
      },
    ],
  },
  browser_close: {
    longDescription:
      'Close an owned browser session and reclaim its resources, returning trace-artifact metadata when tracing was enabled.',
    params: [
      {
        name: 'sessionId',
        type: 'string',
        required: true,
        description: 'Browser session id returned by browser_open.',
      },
    ],
  },
  e2e_plan: {
    longDescription:
      'Create an end-to-end test plan from a feature or user flow. Use it to identify scenarios and acceptance coverage; it plans tests rather than executing them.',
    params: [
      {
        name: 'cwd',
        type: 'string',
        description: 'Directory inside the project to inspect.',
      },
      {
        name: 'framework',
        type: "'all' | 'playwright' | 'cypress'",
        description: 'Optional framework filter; defaults to all.',
      },
      {
        name: 'maxDepth',
        type: 'integer',
        description: 'Maximum workspace discovery depth; defaults to 5.',
      },
      {
        name: 'includeSpecs',
        type: 'boolean',
        description: 'Count and sample specs; defaults to true.',
      },
    ],
    notes: [
      'Use before running browser E2E tests. The result identifies authoritative configs, package scripts, static server hints, specs, and exact argv.',
    ],
  },
};
