// Per-tool detail data for the built-in tool detail pages.
// Generated by scripts/generate-website-tool-catalog.ts from @wrongstack/tools.
// Run `pnpm website:tools:write` after changing a built-in tool contract.

import type { ToolDetail } from './tool-detail-types';

export const toolDetailsPart3: Record<string, ToolDetail> = {
  git: {
    longDescription:
      'Inspect or run scoped Git operations in the project, including status, diff, history, branches, and commits. Review the target and working tree before mutating operations.',
    params: [
      {
        name: 'command',
        type: "'status' | 'log' | 'diff' | 'commit' | 'branch' | 'checkout' | 'stash' | 'push' | 'pull' | 'fetch' | 'reset' | 'worktree'",
        required: true,
        description: 'Git subcommand',
      },
      {
        name: 'files',
        type: 'string',
        description:
          'File(s) for status/diff: single path, comma-separated list, or "**/*.ts" glob',
      },
      {
        name: 'message',
        type: 'string',
        description: 'Commit message (required for commit)',
      },
      {
        name: 'branch',
        type: 'string',
        description: 'Branch name for checkout/branch',
      },
      {
        name: 'format',
        type: "'short' | 'oneline' | 'stat' | 'graph'",
        description: 'Log format (default: short)',
      },
      {
        name: 'limit',
        type: 'integer',
        description: 'Limit for log (default: 20)',
      },
      {
        name: 'dry_run',
        type: 'boolean',
        description: 'For commit: show what would be committed',
      },
      {
        name: 'worktreeAction',
        type: "'list' | 'add' | 'remove' | 'prune'",
        description: 'Worktree action: list, add, remove, prune',
      },
      {
        name: 'worktreePath',
        type: 'string',
        description: 'Path for worktree add/remove (e.g. "../wt-feature-xyz")',
      },
      {
        name: 'newBranch',
        type: 'boolean',
        description: 'Create new branch when adding worktree',
      },
      {
        name: 'force',
        type: 'boolean',
        description: 'Force operation (e.g. worktree remove --force)',
      },
    ],
    notes: [
      '`command`: one of the supported subcommands (status, log, diff, commit, etc.)',
      'Use `message` only for commit operations.',
      'Use `files` array for operations that take paths (status, diff, add, etc.).',
    ],
  },
  patch: {
    longDescription:
      'Apply a unified diff to project files with patch-style context checking. Use it for a reviewed multi-file change when exact patch content is available.',
    params: [
      {
        name: 'patch',
        type: 'string',
        required: true,
        description: 'Unified diff patch content',
      },
      {
        name: 'directory',
        type: 'string',
        description: 'Root directory for patch (default: cwd)',
      },
      {
        name: 'strip',
        type: 'integer',
        description: 'Strip leading path components (default: 1)',
      },
      {
        name: 'dry_run',
        type: 'boolean',
        description: 'Preview without applying',
      },
    ],
    doNotUseWhen: ['you do not already have a unified diff or only need one precise replacement.'],
    useInstead: ['edit'],
    notes: [
      'Use `dry_run: true` to see what would happen without modifying files.',
      'On failure it creates .rej and .orig files for manual review.',
    ],
  },
  json: {
    longDescription:
      'Read, query, validate, or merge JSON/JSON5/YAML files while preserving valid structure (read-only — does not write). Use it instead of raw text edits when reading or querying structured data.',
    params: [
      {
        name: 'action',
        type: "'parse' | 'query' | 'validate' | 'transform' | 'merge'",
        description:
          'Operation (default: parse). parse=read/pretty-print, query=JMESPath, validate=schema, transform=chained queries, merge=deep merge.',
      },
      {
        name: 'file',
        type: 'string',
        description: 'Path to a JSON file (parse/query/validate/transform)',
      },
      {
        name: 'data',
        type: 'string',
        description: 'JSON string (parse/query/validate/transform, alternative to file)',
      },
      {
        name: 'format',
        type: "'json' | 'json5' | 'yaml'",
        description: 'Output format for parse/query/transform (default: json)',
      },
      {
        name: 'query',
        type: 'string',
        description: 'JMESPath-like query expression (query action)',
      },
      {
        name: 'transforms',
        type: 'string[]',
        description: 'Ordered JMESPath query strings (transform action)',
      },
      {
        name: 'schema',
        type: 'object',
        description: 'JSON Schema to validate against (validate action)',
      },
      {
        name: 'base',
        type: 'unknown',
        description: 'Base JSON object (merge action)',
      },
      {
        name: 'patch',
        type: 'unknown',
        description: 'Patch JSON object to merge in (merge action)',
      },
      {
        name: 'conflictResolution',
        type: "'prefer-base' | 'prefer-patch'",
        description: 'Merge conflict resolution (default: prefer-patch)',
      },
      {
        name: 'validate',
        type: 'boolean',
        description: 'Validate syntax only, no output (parse action, default: false)',
      },
    ],
    notes: [
      '`action: "parse"` (default): read/pretty-print/convert JSON, JSON5, or YAML from `file` or `data`.',
      '`action: "query"`: JMESPath-like query (`a.b[0].c`, `items[*].name`, filters, functions).',
      '`action: "validate"`: validate data against a JSON Schema (`schema` param).',
    ],
  },
  diff: {
    longDescription:
      'Show file content with line numbers, staged/working-tree diffs via git, or commit/branch diffs. A safer and more structured alternative to raw `git diff` via shell.',
    params: [
      {
        name: 'path',
        type: 'string',
        description: 'Working directory for the diff operation (defaults to project root).',
      },
      {
        name: 'files',
        type: 'string',
        description: 'Files or globs to diff (e.g. "src/**/*.ts" or comma-separated list).',
      },
      {
        name: 'a',
        type: 'string',
        description: 'First ref/commit/branch for git diff (e.g. HEAD, main, a commit hash).',
      },
      {
        name: 'b',
        type: 'string',
        description: 'Second ref/commit/branch for git diff.',
      },
      {
        name: 'staged',
        type: 'boolean',
        description: 'If true, only show changes that are staged in git.',
      },
      {
        name: 'mode',
        type: "'unified' | 'side-by-side' | 'stat'",
        description:
          'Output format for the git-diff path. "unified" is default; "stat" shows a summary only; "side-by-side" is not supported and falls back to unified. The `files`-only dump path ignores this.',
      },
      {
        name: 'context',
        type: 'integer',
        description:
          'Number of context lines for git unified diffs (default: 3, passed as -U<n>). Ignored by the `files`-only dump path.',
      },
    ],
    notes: [
      '`files` + no `a`/`b` → show file content with line numbers (NOT a unified diff; no +/- prefixes).',
      '`a` and/or `b` → git-style commit/branch diff (unified format, real +/- prefixes).',
      '`staged: true` → only show staged changes.',
    ],
  },
  tree: {
    longDescription:
      'Render a bounded directory tree with depth, file, hidden-file, and ignore controls. Use it for repository orientation without reading every file.',
    params: [
      {
        name: 'path',
        type: 'string',
        description: 'Root directory to display the tree from (defaults to project root).',
      },
      {
        name: 'depth',
        type: 'integer',
        description: 'Maximum directory depth to traverse (default 3, use 0 for unlimited).',
      },
      {
        name: 'glob',
        type: 'string',
        description: 'Only include files matching this glob pattern.',
      },
      {
        name: 'exclude',
        type: 'string[]',
        description: 'List of directory names to completely ignore.',
      },
      {
        name: 'show_files',
        type: 'boolean',
        description: 'Whether to show individual files (default true).',
      },
      {
        name: 'show_dirs',
        type: 'boolean',
        description: 'Whether to show directories (default true).',
      },
      {
        name: 'show_hidden',
        type: 'boolean',
        description: 'Show hidden files starting with . (default: false)',
      },
      {
        name: 'max_entries',
        type: 'integer',
        description: 'Maximum entries retained in the rendered tree (default 5000).',
      },
    ],
    notes: [
      'Call early when working with an unfamiliar project or module.',
      'Tune `depth` (default 3) and use `glob`/`exclude` to focus the view.',
      'Prefer this over raw `bash find` or `glob` + manual reading when you need a quick structural overview.',
    ],
  },
  lint: {
    longDescription:
      'Run the project’s configured linter for a target path or working directory and return diagnostics. Use it after code edits to catch style and static-analysis issues.',
    params: [
      {
        name: 'files',
        type: 'string',
        description:
          'Files/patterns: single path, comma-separated list, or glob (e.g. "src/**/*.ts")',
      },
      {
        name: 'fix',
        type: 'boolean',
        description: 'Auto-fix fixable issues (default: false)',
      },
      {
        name: 'linter',
        type: "'biome' | 'eslint' | 'tslint' | 'auto'",
        description: 'Linter to use (default: auto-detect)',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
    ],
    notes: [
      '`fix: true` will automatically correct what it can.',
      'Target specific files or globs when you only want to check part of the project.',
    ],
  },
  format: {
    longDescription:
      'Run the project’s configured formatter on selected files or directories. Use it after editing code, while reviewing the resulting diff for unintended formatting scope.',
    params: [
      {
        name: 'files',
        type: 'string',
        description: 'Files/patterns: single path, comma-separated list, or glob',
      },
      {
        name: 'fixer',
        type: "'biome' | 'prettier' | 'auto'",
        description: 'Formatter to use (default: auto-detect)',
      },
      {
        name: 'check',
        type: 'boolean',
        description: 'Verify only, do not modify files (default: false)',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
    ],
    notes: [
      'Use on changed files before committing.',
      '`check: true` verifies formatting without making changes (useful in CI-like flows).',
    ],
  },
  typecheck: {
    longDescription:
      'Run TypeScript type checking for an auto-detected or specified tsconfig. Use it after type-affecting changes; it reports diagnostics without writing source files.',
    params: [
      {
        name: 'project',
        type: 'string',
        description: 'Path to tsconfig.json (default: auto-detect)',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
      {
        name: 'strict',
        type: 'boolean',
        description: 'Add --strict flag for maximum type checking (default: false)',
      },
      {
        name: 'all',
        type: 'boolean',
        description:
          'Type-check all workspace packages (pnpm workspaces run `pnpm -r exec tsc --noEmit`; other setups run a single `tsc --noEmit` at cwd) (default: false)',
      },
    ],
    notes: [
      'Use this to catch type errors early.',
      'In monorepos, `all: true` will check every package.',
      'This is one of the most important quality gates in this project.',
    ],
  },
  test: {
    longDescription:
      'Run the detected test runner for selected tests, with optional name filtering, coverage, watch, and timeout controls. Prefer focused tests first, then broader validation as needed.',
    params: [
      {
        name: 'files',
        type: 'string',
        description: 'Test files: single path, comma-separated list, or glob (e.g. "**/*.test.ts")',
      },
      {
        name: 'runner',
        type: "'vitest' | 'jest' | 'mocha' | 'auto'",
        description: 'Test runner (default: auto-detect)',
      },
      {
        name: 'coverage',
        type: 'boolean',
        description: 'Generate coverage report (default: false)',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
      {
        name: 'grep',
        type: 'string',
        description: 'Filter tests by name pattern (default: none)',
      },
      {
        name: 'timeout',
        type: 'integer',
        description: 'Test timeout in ms (default: 30000)',
      },
      {
        name: 'verbose',
        type: 'boolean',
        description:
          'Per-test verbose reporter output (default: false — the summary reporter is used; full output is always saved to a log file referenced in the result)',
      },
    ],
    notes: [
      'Use `files` or `grep` to run only relevant tests during development.',
      '`coverage: true` is useful when working on critical paths.',
    ],
  },
  language_info: {
    longDescription:
      'Inspect detected language tooling, workspaces, and supported operations for the project or target path. Use it before invoking language-specific tooling.',
    params: [
      {
        name: 'action',
        type: "'detect' | 'plan' | 'capabilities'",
        required: true,
        description: 'Read-only action to perform.',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Directory inside the project to inspect.',
      },
      {
        name: 'target',
        type: 'string',
        description: 'Optional target file used for workspace selection.',
      },
      {
        name: 'language',
        type: "'typescript' | 'javascript' | 'go' | 'rust' | 'php' | 'csharp' | 'python' | 'java' | 'ruby' | 'c' | 'cpp' | 'swift' | 'dart' | 'elixir' | 'deno' | 'shell'",
        description: 'Optional language profile filter.',
      },
      {
        name: 'workspace',
        type: 'string',
        description: 'Workspace id or root returned by detect.',
      },
      {
        name: 'operation',
        type: "'syntax' | 'semantic' | 'lint' | 'format-check' | 'format-write' | 'test-compile' | 'test' | 'build' | 'run' | 'debug-compile' | 'debug-test' | 'debug-runtime' | 'debug-race' | 'package-install' | 'package-add' | 'package-remove' | 'package-update' | 'package-audit' | 'package-outdated'",
        description: 'Operation to preview when action=plan.',
      },
      {
        name: 'mode',
        type: "'fast' | 'standard' | 'thorough'",
        description: 'Planning mode.',
      },
      {
        name: 'options',
        type: 'object',
        description: 'Action-specific planning options used only when action=plan.',
      },
    ],
    doNotUseWhen: ['You need to execute a compiler, test runner, formatter, or package manager.'],
    useInstead: ['exec', 'typecheck', 'lint', 'format', 'test', 'install'],
    notes: [
      'Use `detect` to find TypeScript/JavaScript, Go, Rust, PHP, and C# workspaces. Use `plan` to obtain an exact, validated argv plan before choosing an execution tool.',
    ],
  },
  language: {
    longDescription:
      'Run a supported language-tooling operation in a detected workspace. Use it when the language profile provides a safer, structured alternative to an arbitrary shell command.',
    params: [
      {
        name: 'action',
        type: "'check' | 'lint' | 'format' | 'test' | 'build' | 'debug'",
        required: true,
        description: 'Language operation to execute.',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Directory inside the project.',
      },
      {
        name: 'target',
        type: 'string',
        description: 'Optional target file for workspace selection.',
      },
      {
        name: 'language',
        type: "'typescript' | 'javascript' | 'go' | 'rust' | 'php' | 'csharp' | 'python' | 'java' | 'ruby' | 'c' | 'cpp' | 'swift' | 'dart' | 'elixir' | 'deno' | 'shell'",
        description: 'Optional language filter.',
      },
      {
        name: 'workspace',
        type: 'string',
        description: 'Detected workspace id or root.',
      },
      {
        name: 'mode',
        type: "'fast' | 'standard' | 'thorough'",
        description: 'Execution depth; thorough may run more checks.',
      },
      {
        name: 'check',
        type: "'syntax' | 'semantic' | 'all'",
        description: 'Check type when action=check.',
      },
      {
        name: 'formatCheck',
        type: 'boolean',
        description: 'Verify formatting without writing (default true).',
      },
      {
        name: 'filter',
        type: 'string',
        description: 'Validated test/debug filter passed to profile adapters.',
      },
      {
        name: 'coverage',
        type: 'boolean',
        description: 'Coverage request; currently rejected until the language runner supports it.',
      },
      {
        name: 'noRun',
        type: 'boolean',
        description: 'Compile tests without running when supported.',
      },
      {
        name: 'debug',
        type: "'compile' | 'test' | 'runtime' | 'race'",
        description: 'Debug evidence mode when action=debug.',
      },
    ],
    doNotUseWhen: ['You only need workspace detection/planning, or need to modify dependencies.'],
    useInstead: ['language_info', 'install', 'audit', 'outdated'],
    notes: [
      'Use this instead of constructing compiler or test commands manually. The tool detects the workspace, builds an allowlisted argv plan, revalidates it, executes without a shell, and returns normalized diagnostics.',
    ],
  },
  language_package: {
    longDescription:
      'Plan or perform a dependency operation through the detected package ecosystem. Use dry-run first when possible and specify the workspace or dependency scope deliberately.',
    params: [
      {
        name: 'operation',
        type: "'install' | 'add' | 'remove' | 'update' | 'audit' | 'outdated'",
        required: true,
        description: 'Package management operation to perform.',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Directory inside the project.',
      },
      {
        name: 'language',
        type: "'typescript' | 'javascript' | 'go' | 'rust' | 'php' | 'csharp' | 'python' | 'java' | 'ruby' | 'c' | 'cpp' | 'swift' | 'dart' | 'elixir' | 'deno' | 'shell'",
        description: 'Optional language profile filter.',
      },
      {
        name: 'workspace',
        type: 'string',
        description: 'Detected workspace id or root.',
      },
      {
        name: 'names',
        type: 'string[]',
        description:
          'Validated package names. Required for add/remove/update; optional for install.',
      },
      {
        name: 'scope',
        type: "'runtime' | 'development' | 'optional'",
        description: 'Where to record the dependency (add/update).',
      },
      {
        name: 'dryRun',
        type: 'boolean',
        description: 'Preview the install without modifying the workspace.',
      },
      {
        name: 'allowScripts',
        type: 'boolean',
        description:
          'Opt in to running package lifecycle scripts (preinstall/install/postinstall). Default false.',
      },
    ],
    doNotUseWhen: [
      'You only need to inspect or plan, or need to compile/test/lint without touching dependencies.',
    ],
    useInstead: ['language_info', 'language', 'install', 'audit', 'outdated'],
    notes: [
      'Use this instead of the legacy `install`/`audit`/`outdated` tools. The tool detects the workspace, builds an allowlisted argv plan with lifecycle scripts disabled, runs it, and records manifest/lockfile changes.',
    ],
  },
  install: {
    longDescription:
      'Install project dependencies with the detected package manager. Use only when dependency changes are required, and inspect lockfile and manifest changes afterward.',
    params: [
      {
        name: 'packages',
        type: 'string',
        description:
          'Package(s) to install: single name, comma-separated list, or empty for all deps',
      },
      {
        name: 'save',
        type: "'dependency' | 'dev' | 'optional'",
        description:
          'Where to save the package(s): "dependency", "devDependencies", or "optionalDependencies".',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory for the install command (must stay inside project).',
      },
      {
        name: 'dry_run',
        type: 'boolean',
        description:
          'If true, show what would be installed without actually modifying package.json or node_modules.',
      },
      {
        name: 'global',
        type: 'boolean',
        description: 'Whether to perform a global install (use with caution).',
      },
      {
        name: 'lifecycleScripts',
        type: 'boolean',
        description:
          'Opt in to running package lifecycle scripts (preinstall / install / postinstall / prepare / …). Default: false — installs pass --ignore-scripts so a malicious package cannot execute arbitrary code at install time. Set true to opt back in to the legacy npm/pnpm/yarn default.',
      },
    ],
    notes: [
      'Empty `packages` → normal `install` (respects lockfile).',
      'Provide names → adds/updates specific packages.',
      '`dry_run: true` for safe preview.',
    ],
  },
  audit: {
    longDescription:
      'Run the package manager’s dependency vulnerability audit and summarize actionable findings. Use it to assess known dependency advisories, not source-code vulnerabilities.',
    params: [
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
      {
        name: 'level',
        type: "'low' | 'moderate' | 'high' | 'critical'",
        description: 'Minimum severity level to report',
      },
      {
        name: 'fix',
        type: 'boolean',
        description:
          'Deprecated and rejected — this tool is read-only and never modifies dependencies. Use `install` (or `language_package`) to remediate vulnerabilities.',
      },
    ],
    notes: [
      'Run regularly and especially before any release.',
      'Use `level` to focus on high/critical issues.',
      'This tool is read-only: to remediate, use `install` (or `language_package`) to upgrade the affected packages.',
    ],
  },
  outdated: {
    longDescription:
      'List outdated project dependencies and available versions without changing manifests or lockfiles. Use it to plan dependency maintenance.',
    params: [
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
    ],
    notes: [
      'Run periodically or before dependency-related work.',
      'Helps surface packages that may need updates for security or features.',
      'Hits the package registry over HTTP, so it is NOT purely local — flagged as mutating for the confirmation gate.',
    ],
  },
  logs: {
    longDescription:
      'Read or tail configured local, container, or process logs with bounded output. Use it to investigate a known runtime failure or service behavior.',
    params: [
      {
        name: 'service',
        type: 'string',
        description: 'Docker container name (passed to `docker logs`)',
      },
      {
        name: 'path',
        type: 'string',
        description: 'Path to log file (alternative to service)',
      },
      {
        name: 'lines',
        type: 'integer',
        description: 'Number of log lines to fetch (default: 100, 0 for all)',
      },
      {
        name: 'filter',
        type: 'string',
        description: 'Regex pattern to filter log lines',
      },
      {
        name: 'since',
        type: "'1h' | '6h' | '24h' | 'all'",
        description: 'Only show Docker logs since duration (ignored for files; "all" = no limit)',
      },
      {
        name: 'cwd',
        type: 'string',
        description: 'Working directory (default: cwd)',
      },
    ],
    notes: [
      'Prefer `path` for local files or `service` for Docker containers.',
      'Always use `filter` (regex) when possible to reduce noise and token usage.',
    ],
  },
  design: {
    longDescription:
      'Choose, preview, or materialize a UI design kit (e.g. minimal-clarity, neo-brutalist) for the active stack. Lists available kits, previews tokens, or writes a design-token source file to the project.',
    params: [
      {
        name: 'action',
        type: "'list' | 'use' | 'foundations' | 'set' | 'tune' | 'materialize' | 'verify'",
        description:
          'list = menu; use = load+pin a kit; foundations = baseline; set = override colors/tokens; tune = high-level knobs (radius/density/font/motion); materialize = write tokens to a theme file; verify = scan UI for token drift. Default: list.',
      },
      {
        name: 'kit',
        type: 'string',
        description: 'Kit id (required for "use"), e.g. "minimal-clarity", "neo-brutalist".',
      },
      {
        name: 'stack',
        type: "'web' | 'react-native' | 'flutter' | 'swiftui' | 'compose'",
        description: 'Target stack — narrows guidance + materialize format. Default: web.',
      },
      {
        name: 'set',
        type: 'object',
        description:
          'Token overrides for "set"/"use": { "primary": "oklch(…)", "dark.bg": "#111" }. Bare key = both themes; "light."/"dark." prefix = that theme only. Empty value clears an override.',
      },
      {
        name: 'tune',
        type: 'object',
        description:
          'High-level knobs for "tune": { "radius": "lg", "density": "compact", "font": "Space Grotesk", "motion": "snappy" }. radius = none|sm|md|lg|xl|full or a base length; density = compact|cozy|comfortable; motion = snappy|smooth|none. Resolved to concrete token overrides.',
      },
      {
        name: 'out',
        type: 'string',
        description:
          'Materialize output path (project-relative). Defaults to a per-stack convention.',
      },
      {
        name: 'force',
        type: 'boolean',
        description:
          'Materialize: overwrite an existing file (default false — refuses to clobber).',
      },
      {
        name: 'files',
        type: 'string[]',
        description:
          'Verify: explicit project-relative files to scan. Default: a bounded UI-file walk.',
      },
    ],
    notes: [
      'Flow: `design {action:"use", kit:"minimal-clarity", stack:"web"}` → optionally `design {action:"set", set:{primary:"oklch(62% 0.2 25)"}}` → `design {action:"materialize"}` to write tokens to disk → implement against them → `design {action:"verify"}`.',
    ],
  },
};
