import type { CliContext } from './cli-context.js';
import { bootCliRuntime } from './cli-main-boot.js';
import { wireCliOrchestration } from './cli-main-orchestration.js';
import type { CliConfigState } from './cli-main-state.js';
import { CLI_VERSION } from './version.js';
import { runCliExecution } from './wiring/cli-execute-builder.js';

export { CLI_VERSION };

/**
 * Everything the CLI needs once it knows it is running an interactive session.
 */
export async function runInteractive(cliCtx: CliContext): Promise<number> {
  const state: CliConfigState = { config: cliCtx.config };
  const boot = await bootCliRuntime(cliCtx, state);
  if (boot.kind === 'exit') return boot.code;
  const orchestration = await wireCliOrchestration(cliCtx, state, boot);
  const {
    vault,
    wpaths,
    projectRoot,
    flags,
    positional,
    modelsRegistry,
    renderer,
    reader,
    logger,
    needsSetup,
    events,
    container,
    configStore,
    updateInfo,
    webuiSessionChild,
  } = cliCtx;
  const {
    profileConfigPath,
    modeStore,
    resolvedProvider,
    modeId,
    providerAuthRegistry,
    memoryStore,
    teardownHandlers,
    vectorMemoryStore,
    vectorMemoryModelCacheDir,
    skillLoader,
    promptLoader,
    sessionRef,
    sessionStore,
    tokenCounter,
    context,
    session,
    attachments,
    queueStore,
    detachTodosCheckpoint,
    sessResult,
    governanceHandle,
    activateSession,
    sessionBridge,
    stats,
    getActiveReasoningConfig,
    autoCompactor,
    effectiveMaxContextRef,
    applyMaxContext,
    agent,
    mcpRegistry,
    slashRegistry,
    brainMailbox,
    pluginHost,
    statusTracker,
    buildProviderForModel,
    switchProviderAndModel,
    reloadProviderConfig,
  } = boot;
  const {
    run,
    eternalListeners,
    stageListeners,
    agentMonitor,
    brain,
    brainLog,
    brainSettings,
    brainRuntime,
    multiAgentHost,
    fleetStreamController,
    interruptController,
    enhanceController,
    statuslineHiddenItems,
    setStatuslineHiddenItems,
    saveStatuslineHiddenItems,
    statuslineLines,
    setStatuslineLines,
    saveStatuslineLines,
    statuslineDensities,
    setStatuslineDensities,
    saveStatuslineDensities,
    statuslineOrder,
    setStatuslineOrder,
    saveStatuslineOrder,
    onPanelOpen,
    coordinatorController,
    setYoloMode,
    secretInputController,
    sddRunRegistry,
    configRef,
    runSageSessionHygiene,
    getPluginPickerItems,
    togglePluginFromPicker,
    getToolPickerItems,
    savedProviderCfg,
  } = orchestration;

  return runCliExecution({
    agent,
    events,
    slashRegistry,
    tokenCounter,
    sessionRef,
    activateSession,
    config: state.config,
    configStore,
    wpaths,
    projectRoot,
    flags,
    positional,
    webuiSessionChild,
    updateInfo,
    attachments,
    brainMailbox,
    session,
    mcpRegistry,
    queueStore,
    context,
    detachTodosCheckpoint,
    sessResult,
    sessionStore,
    memoryStore,
    vectorMemoryStore,
    vectorMemoryModelCacheDir,
    modeStore,
    needsSetup,
    statusTracker,
    multiAgentHost,
    modelsRegistry,
    savedProviderCfg,
    resolvedProvider,
    logger,
    switchProviderAndModel,
    reloadProviderConfig,
    applyMaxContext,
    renderer,
    reader,
    secretInputController,
    effectiveMaxContextRef,
    stats,
    skillLoader,
    promptLoader,
    modeId,
    director: run.director,
    coordinatorController,
    fleetStreamController,
    agentTranscripts: agentMonitor,
    vault,
    profileConfigPath,
    providerAuthRegistry,
    onPanelOpen,
    interruptController,
    enhanceController,
    activeReasoningConfig: getActiveReasoningConfig(),
    configRef,
    buildProviderForModel,
    statuslineHiddenItems,
    setStatuslineHiddenItems,
    saveStatuslineHiddenItems,
    statuslineLines,
    setStatuslineLines,
    saveStatuslineLines,
    statuslineDensities,
    setStatuslineDensities,
    saveStatuslineDensities,
    statuslineOrder,
    setStatuslineOrder,
    saveStatuslineOrder,
    setYoloMode,
    autonomyMode: run.autonomyMode,
    setAutonomyMode: (mode: typeof run.autonomyMode) => {
      run.autonomyMode = mode;
    },
    nextPredictEnabled: run.nextPredictEnabled,
    setNextPredict: (enabled: boolean) => {
      run.nextPredictEnabled = enabled;
    },
    container,
    sessionBridge,
    autoCompactor,
    getPluginPickerItems,
    togglePluginFromPicker,
    getToolPickerItems,
    brain,
    brainSettings,
    brainRuntime,
    brainLog,
    currentSuggestions: run.currentSuggestions,
    setCurrentSuggestions: (suggestions: typeof run.currentSuggestions) => {
      run.currentSuggestions = suggestions;
    },
    eternalEngine: run.eternalEngine,
    parallelEngine: run.parallelEngine,
    sddRunRegistry,
    eternalListeners,
    stageListeners,
    runSageSessionHygiene,
    pluginHost,
    teardownHandlers,
    governanceHandle,
    setConfig: (nextConfig: typeof state.config) => {
      state.config = nextConfig;
    },
  });
}
