import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  createSecurityReportFilename,
  defaultReportGenerator,
  ReportGenerator,
  resolveReportFormat,
} from '../src/report-generator.js';
import type { Finding, ScanResult } from '../src/scanner.js';

let tmp: string;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'report-gen-'));
});

afterEach(async () => {
  await fs.rm(tmp, { recursive: true, force: true });
});

function mkFinding(over: Partial<Finding> = {}): Finding {
  return {
    title: 'Hard-coded API key',
    severity: 'critical',
    category: 'secrets',
    file: 'src/app.ts',
    line: 42,
    snippet: 'const KEY = "sk-...";',
    remediation: 'Move to environment variable.',
    ...over,
  } as Finding;
}

function mkScanResult(over: Partial<ScanResult> = {}): ScanResult {
  return {
    timestamp: '2026-05-22T10:00:00.000Z',
    projectRoot: '/proj',
    techStack: { stack: 'typescript', packageManager: 'pnpm' } as never,
    scannedFiles: 12,
    scanDurationMs: 1500,
    summary: { critical: 1, high: 1, medium: 0, low: 0, total: 2 },
    findings: [
      mkFinding(),
      mkFinding({
        title: 'XSS risk',
        severity: 'high',
        category: 'injection',
        file: 'src/render.ts',
        line: undefined,
        snippet: undefined,
        remediation: 'Escape user input.',
      }),
    ],
    errors: [],
    ...over,
  } as ScanResult;
}

describe('ReportGenerator', () => {
  it('exposes a default singleton', () => {
    expect(defaultReportGenerator).toBeInstanceOf(ReportGenerator);
  });

  // ── markdown ──────────────────────────────────────────────────────────────

  it('renders a markdown report grouped by severity by default', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const file = await gen.generate(mkScanResult());
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('# Security Scan Report');
    expect(md).toContain('CRITICAL (1)');
    expect(md).toContain('HIGH (1)');
    expect(md).toContain('Hard-coded API key');
    expect(md).toContain('XSS risk');
    // No medium/low sections when empty
    expect(md).not.toContain('MEDIUM (');
    // Footer
    expect(md).toContain('Report generated by security scanner');
  });

  it('groups by category when groupBySeverity=false', async () => {
    const gen = new ReportGenerator({
      outputDir: path.join(tmp, 'reports'),
      groupBySeverity: false,
    });
    const file = await gen.generate(mkScanResult());
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('SECRETS (1)');
    expect(md).toContain('INJECTION (1)');
  });

  it('respects maxFindingsPerCategory when groupBySeverity=false', async () => {
    const gen = new ReportGenerator({
      outputDir: path.join(tmp, 'reports'),
      groupBySeverity: false,
      maxFindingsPerCategory: 1,
    });
    const scanResult = mkScanResult({
      findings: [
        mkFinding({ title: 'Secret 1', category: 'secrets' }),
        mkFinding({ title: 'Secret 2', category: 'secrets' }),
      ],
      summary: { critical: 0, high: 2, medium: 0, low: 0, total: 2 } as never,
    });
    const file = await gen.generate(scanResult);
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('## SECRETS (2)');
    expect(md).toContain('Secret 1');
    expect(md).not.toContain('Secret 2');
  });

  it('omits remediation when includeRemediation=false', async () => {
    const gen = new ReportGenerator({
      outputDir: path.join(tmp, 'reports'),
      includeRemediation: false,
    });
    const file = await gen.generate(mkScanResult());
    const md = await fs.readFile(file, 'utf8');
    expect(md).not.toContain('Remediation:');
  });

  it('renders the "Scan Errors" section when result.errors is non-empty', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const file = await gen.generate(
      mkScanResult({ errors: ['perm denied', 'tool crashed'] } as never),
    );
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('## Scan Errors');
    expect(md).toContain('perm denied');
    expect(md).toContain('tool crashed');
  });

  it('produces a report with empty findings + no errors gracefully', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const file = await gen.generate(
      mkScanResult({
        findings: [],
        errors: [],
        summary: { critical: 0, high: 0, medium: 0, low: 0, total: 0 } as never,
      }),
    );
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('| **Total** | **0** |');
    expect(md).not.toContain('CRITICAL (');
  });

  it('skips snippet rendering when finding.snippet is missing', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const file = await gen.generate(
      mkScanResult({
        findings: [mkFinding({ snippet: undefined, line: undefined, title: 'No snippet' })],
        summary: { critical: 1, high: 0, medium: 0, low: 0, total: 1 } as never,
      }),
    );
    const md = await fs.readFile(file, 'utf8');
    expect(md).toContain('No snippet');
    // No fenced code block
    expect(md.indexOf('```')).toBe(-1);
  });

  // ── json ──────────────────────────────────────────────────────────────────

  it('renders a JSON report when format=json', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports'), format: 'json' });
    const file = await gen.generate(mkScanResult());
    const raw = await fs.readFile(file, 'utf8');
    const parsed = JSON.parse(raw);
    expect(parsed.meta.projectRoot).toBe('/proj');
    expect(parsed.summary.total).toBe(2);
    expect(parsed.findings).toHaveLength(2);
  });

  // ── html ──────────────────────────────────────────────────────────────────

  it('renders an HTML report when format=html', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports'), format: 'html' });
    const file = await gen.generate(mkScanResult());
    const html = await fs.readFile(file, 'utf8');
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('Security Scan Report');
    expect(html).toContain('Hard-coded API key');
    expect(html).toContain('color: #dc2626'); // critical color
    expect(html).toContain('color: #ea580c'); // high color
  });

  // CRIT-002 (bug-hunter) / XSS guard: every finding field flows from
  // untrusted sources (LLM output, file paths, remediation text). Without
  // escaping, an LLM that returns `<script>alert(1)</script>` in `title`
  // would inject executable HTML when the report is served by the WebUI.
  describe('HTML XSS escaping (CRIT-002 fix)', () => {
    it('escapes <, >, &, ", and \' in finding fields', async () => {
      const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports'), format: 'html' });
      const file = await gen.generate(
        mkScanResult({
          findings: [
            mkFinding({
              title: '"><script>alert(1)</script>',
              category: 'injection"onload="x' as Finding['category'],
              file: "src/<bad>&'.ts",
              line: 1,
              remediation: 'Use <safe> & "quoted" text',
            }),
          ],
          summary: { critical: 1, high: 0, medium: 0, low: 0, total: 1 } as never,
        }),
      );
      const html = await fs.readFile(file, 'utf8');

      // The raw payload must NOT appear unescaped anywhere in the HTML body
      expect(html).not.toContain('<script>alert(1)</script>');
      expect(html).not.toContain('"onload="x');
      expect(html).not.toContain("src/<bad>&'.ts");

      // It must appear in escaped form
      expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
      expect(html).toContain('&quot;&gt;'); // ">  → &quot;&gt;
      expect(html).toContain('&amp;');
      expect(html).toContain('&#39;');
    });

    it('escapes projectRoot, techStack, and timestamp in header', async () => {
      const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports'), format: 'html' });
      const file = await gen.generate(
        mkScanResult({
          projectRoot: '/proj/<x>',
          techStack: { stack: 'type<script>', packageManager: 'pn&pm' } as never,
        }),
      );
      const html = await fs.readFile(file, 'utf8');
      expect(html).not.toContain('/proj/<x>');
      expect(html).not.toContain('type<script>');
      expect(html).not.toContain('pn&pm');
      expect(html).toContain('&lt;x&gt;');
      expect(html).toContain('pn&amp;pm');
    });

    it('falls back to black when severity is unknown (no undefined CSS)', async () => {
      // The map lookup `severityColors[f.severity]` previously produced
      // `undefined` for unknown severities, which would emit `color: undefined;`
      // into the style attribute. Now it falls back to #000000.
      const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports'), format: 'html' });
      const file = await gen.generate(
        mkScanResult({
          findings: [mkFinding({ severity: 'gibberish' as never })],
          summary: { critical: 0, high: 0, medium: 0, low: 0, total: 1 } as never,
        }),
      );
      const html = await fs.readFile(file, 'utf8');
      expect(html).not.toMatch(/color:\s*undefined/i);
      expect(html).toContain('color: #000000');
    });
  });

  // ── output directory creation ────────────────────────────────────────────

  it('creates the output directory when it does not exist', async () => {
    const outDir = path.join(tmp, 'nested', 'a', 'b');
    const gen = new ReportGenerator({ outputDir: outDir });
    const file = await gen.generate(mkScanResult());
    expect(file.startsWith(outDir)).toBe(true);
    const exists = await fs
      .stat(outDir)
      .then(() => true)
      .catch(() => false);
    expect(exists).toBe(true);
  });

  it('reuses an existing output directory', async () => {
    const outDir = path.join(tmp, 'exists');
    await fs.mkdir(outDir, { recursive: true });
    const gen = new ReportGenerator({ outputDir: outDir });
    const file = await gen.generate(mkScanResult());
    expect(file.startsWith(outDir)).toBe(true);
  });

  it('does not overwrite reports generated in the same second', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const [first, second] = await Promise.all([
      gen.generate(mkScanResult({ projectRoot: '/first' })),
      gen.generate(mkScanResult({ projectRoot: '/second' })),
    ]);

    expect(first).not.toBe(second);
    await expect(fs.readFile(first, 'utf8')).resolves.toContain('/first');
    await expect(fs.readFile(second, 'utf8')).resolves.toContain('/second');
  });

  it('embeds an ISO-style timestamp in the filename', async () => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, 'reports') });
    const file = await gen.generate(mkScanResult());
    // Replace : and . with - → 2026-05-22T10-00-00 style
    expect(path.basename(file)).toMatch(
      /^security-report-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-[0-9a-f]{8}\.markdown$/,
    );
  });
});

// ── format validation ───────────────────────────────────────────────────────
// `createSecurityReportFilename` interpolates `format` into a filename segment
// that callers `path.join` against an output directory, and `path.join`
// normalizes `..` and separator segments away. The declared
// `ReportOptions['format']` union is erased at runtime, so the union must be
// enforced by a membership test at that choke point — an out-of-union value
// once wrote a report outside the output directory and left it empty.

describe('resolveReportFormat', () => {
  it('passes the declared union through unchanged', () => {
    expect(resolveReportFormat('markdown')).toBe('markdown');
    expect(resolveReportFormat('json')).toBe('json');
    expect(resolveReportFormat('html')).toBe('html');
  });

  it.each([
    ['a traversal payload', 'x/../../escape.md'],
    ['a parent-relative escape', '../../evil.md'],
    ['a windows-style escape', 'x\\..\\..\\escape.md'],
    ['a bare separator', '/'],
    ['a separator-prefixed path', '/etc/passwd'],
    ['a non-union word', 'xml'],
    ['an almost-correct case', 'Markdown'],
    ['an empty string', ''],
    ['a non-string', 42],
    ['null', null],
    ['undefined', undefined],
    ['an object', { toString: () => 'json' }],
  ])('rejects %s and falls back to markdown', (_label, value) => {
    const resolved = resolveReportFormat(value);
    expect(resolved).toBe('markdown');
    expect(['markdown', 'json', 'html']).toContain(resolved);
  });
});

describe('createSecurityReportFilename', () => {
  it.each(['markdown', 'json', 'html'] as const)('emits the %s extension as given', (format) => {
    expect(createSecurityReportFilename(format)).toMatch(
      new RegExp(
        `^security-report-\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-[0-9a-f]{8}\\.${format}$`,
      ),
    );
  });

  it.each([
    'x/../../escape.md',
    '../../evil.md',
    'x\\..\\..\\escape.md',
    '/',
    '/etc/passwd',
    'xml',
    '',
  ])('never leaks separators or dot-segments for %j', (hostile) => {
    const name = createSecurityReportFilename(hostile as never);
    // The invariant that matters: the returned string is ONE filename segment.
    expect(name).not.toContain('/');
    expect(name).not.toContain('\\');
    expect(name).not.toContain('..');
    expect(path.basename(name)).toBe(name);
    expect(name).toMatch(
      /^security-report-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-[0-9a-f]{8}\.markdown$/,
    );
  });

  it('cannot be walked out of an output directory by path.join', () => {
    const outputDir = path.join(tmp, 'security-reports');
    for (const hostile of ['x/../../escape.md', '../../evil.md', 'x/../../../escape.md']) {
      const filepath = path.join(outputDir, createSecurityReportFilename(hostile as never));
      expect(path.dirname(filepath)).toBe(outputDir);
      expect(path.resolve(filepath).startsWith(path.resolve(outputDir) + path.sep)).toBe(true);
    }
  });
});

describe('ReportGenerator derives content and extension from one validated value', () => {
  it.each([
    ['markdown', /\.markdown$/, '# Security Scan Report'],
    ['json', /\.json$/, '"findings"'],
    ['html', /\.html$/, '<!DOCTYPE html>'],
  ] as const)('%s writes %s content under a %s name', async (format, ext, body) => {
    const gen = new ReportGenerator({ outputDir: path.join(tmp, `agree-${format}`), format });
    const file = await gen.generate(mkScanResult());
    expect(file).toMatch(ext);
    const content = await fs.readFile(file, 'utf8');
    expect(content).toContain(body);
  });

  it.each([
    ['a traversal payload', 'x/../../escape.md'],
    ['a parent-relative escape', '../../evil.md'],
    ['a non-union word', 'xml'],
  ])('an out-of-union format (%s) keeps the report inside the output dir', async (_l, hostile) => {
    const outDir = path.join(tmp, `pinned-${encodeURIComponent(hostile)}`);
    const gen = new ReportGenerator({ outputDir: outDir, format: hostile as never });
    const file = await gen.generate(mkScanResult());

    // Inside the output directory...
    expect(path.dirname(file)).toBe(outDir);
    // ...with a single-segment name...
    expect(path.basename(file)).toBe(path.basename(file).replace(/[\\/]/g, ''));
    // ...and the content generator AGREES with the extension. Before the fix
    // the two were derived independently, so a hostile format produced a
    // `.json` name over a markdown body (or vice versa).
    expect(file).toMatch(/\.markdown$/);
    const content = await fs.readFile(file, 'utf8');
    expect(content).toContain('# Security Scan Report');
    expect(content).not.toContain('<!DOCTYPE html>');
    expect(() => JSON.parse(content)).toThrow();
  });

  it('leaves no stray file outside the output directory', async () => {
    const outDir = path.join(tmp, 'stray-check');
    const gen = new ReportGenerator({ outputDir: outDir, format: 'x/../../escape.md' as never });
    await gen.generate(mkScanResult());
    const entries = await fs.readdir(tmp);
    expect(entries.filter((e) => e === 'escape.md')).toEqual([]);
    expect(entries.sort()).toEqual(['stray-check']);
  });
});
